/*
* generated by Xtext
*/
package de.nie.fin;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class FinUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.nie.fin.ui.internal.FinActivator.getInstance().getInjector("de.nie.fin.Fin");
	}
	
}
