/*
* generated by Xtext
*/
package de.nie.fin.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class FinOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
