/*
* generated by Xtext
*/

package de.nie.fin.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.xbase.services.XbaseGrammarAccess;
import org.eclipse.xtext.xbase.services.XtypeGrammarAccess;

@Singleton
public class FinGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class FinModelFileElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FinModelFile");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Keyword cPackageKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cNameAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cNameQualifiedNameParserRuleCall_0_1_0 = (RuleCall)cNameAssignment_0_1.eContents().get(0);
		private final Assignment cImportsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cImportsImportParserRuleCall_1_0 = (RuleCall)cImportsAssignment_1.eContents().get(0);
		private final Assignment cElementsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cElementsElementParserRuleCall_2_0 = (RuleCall)cElementsAssignment_2.eContents().get(0);
		
		//FinModelFile:
		//
		//	("package" name=QualifiedName)? imports+=Import* elements+=Element*;
		public ParserRule getRule() { return rule; }

		//("package" name=QualifiedName)? imports+=Import* elements+=Element*
		public Group getGroup() { return cGroup; }

		//("package" name=QualifiedName)?
		public Group getGroup_0() { return cGroup_0; }

		//"package"
		public Keyword getPackageKeyword_0_0() { return cPackageKeyword_0_0; }

		//name=QualifiedName
		public Assignment getNameAssignment_0_1() { return cNameAssignment_0_1; }

		//QualifiedName
		public RuleCall getNameQualifiedNameParserRuleCall_0_1_0() { return cNameQualifiedNameParserRuleCall_0_1_0; }

		//imports+=Import*
		public Assignment getImportsAssignment_1() { return cImportsAssignment_1; }

		//Import
		public RuleCall getImportsImportParserRuleCall_1_0() { return cImportsImportParserRuleCall_1_0; }

		//elements+=Element*
		public Assignment getElementsAssignment_2() { return cElementsAssignment_2; }

		//Element
		public RuleCall getElementsElementParserRuleCall_2_0() { return cElementsElementParserRuleCall_2_0; }
	}

	public class ImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Import");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cImportKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cImportedNamespaceAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cImportedNamespaceQualifiedNameParserRuleCall_1_0 = (RuleCall)cImportedNamespaceAssignment_1.eContents().get(0);
		
		//Import:
		//
		//	"import" importedNamespace=QualifiedName;
		public ParserRule getRule() { return rule; }

		//"import" importedNamespace=QualifiedName
		public Group getGroup() { return cGroup; }

		//"import"
		public Keyword getImportKeyword_0() { return cImportKeyword_0; }

		//importedNamespace=QualifiedName
		public Assignment getImportedNamespaceAssignment_1() { return cImportedNamespaceAssignment_1; }

		//QualifiedName
		public RuleCall getImportedNamespaceQualifiedNameParserRuleCall_1_0() { return cImportedNamespaceQualifiedNameParserRuleCall_1_0; }
	}

	public class ElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Element");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cKontoParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cBuchungParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cEmpfaengerParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cBuchungsintervallParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cKategorieParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//Element:
		//
		//	Konto | Buchung | Empfaenger | Buchungsintervall | Kategorie;
		public ParserRule getRule() { return rule; }

		//Konto | Buchung | Empfaenger | Buchungsintervall | Kategorie
		public Alternatives getAlternatives() { return cAlternatives; }

		//Konto
		public RuleCall getKontoParserRuleCall_0() { return cKontoParserRuleCall_0; }

		//Buchung
		public RuleCall getBuchungParserRuleCall_1() { return cBuchungParserRuleCall_1; }

		//Empfaenger
		public RuleCall getEmpfaengerParserRuleCall_2() { return cEmpfaengerParserRuleCall_2; }

		//Buchungsintervall
		public RuleCall getBuchungsintervallParserRuleCall_3() { return cBuchungsintervallParserRuleCall_3; }

		//Kategorie
		public RuleCall getKategorieParserRuleCall_4() { return cKategorieParserRuleCall_4; }
	}

	public class KontoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Konto");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cKontoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameValidIDParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cKtoNrKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cKtoNrAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cKtoNrINTTerminalRuleCall_4_0 = (RuleCall)cKtoNrAssignment_4.eContents().get(0);
		private final Keyword cBlzKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cBlzAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cBlzINTTerminalRuleCall_6_0 = (RuleCall)cBlzAssignment_6.eContents().get(0);
		private final Keyword cBankKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cBankAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cBankSTRINGTerminalRuleCall_8_0 = (RuleCall)cBankAssignment_8.eContents().get(0);
		private final Keyword cVerwendungKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cVerwendungAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cVerwendungSTRINGTerminalRuleCall_10_0 = (RuleCall)cVerwendungAssignment_10.eContents().get(0);
		private final Keyword cInhaberKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cInhaberAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cInhaberSTRINGTerminalRuleCall_12_0 = (RuleCall)cInhaberAssignment_12.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Konto:
		//
		//	"Konto" name=ValidID "{" "KtoNr" ktoNr=INT "Blz" blz=INT "Bank" bank=STRING "Verwendung" verwendung=STRING "Inhaber"
		//
		//	inhaber=STRING "}";
		public ParserRule getRule() { return rule; }

		//"Konto" name=ValidID "{" "KtoNr" ktoNr=INT "Blz" blz=INT "Bank" bank=STRING "Verwendung" verwendung=STRING "Inhaber"
		//
		//inhaber=STRING "}"
		public Group getGroup() { return cGroup; }

		//"Konto"
		public Keyword getKontoKeyword_0() { return cKontoKeyword_0; }

		//name=ValidID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ValidID
		public RuleCall getNameValidIDParserRuleCall_1_0() { return cNameValidIDParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"KtoNr"
		public Keyword getKtoNrKeyword_3() { return cKtoNrKeyword_3; }

		//ktoNr=INT
		public Assignment getKtoNrAssignment_4() { return cKtoNrAssignment_4; }

		//INT
		public RuleCall getKtoNrINTTerminalRuleCall_4_0() { return cKtoNrINTTerminalRuleCall_4_0; }

		//"Blz"
		public Keyword getBlzKeyword_5() { return cBlzKeyword_5; }

		//blz=INT
		public Assignment getBlzAssignment_6() { return cBlzAssignment_6; }

		//INT
		public RuleCall getBlzINTTerminalRuleCall_6_0() { return cBlzINTTerminalRuleCall_6_0; }

		//"Bank"
		public Keyword getBankKeyword_7() { return cBankKeyword_7; }

		//bank=STRING
		public Assignment getBankAssignment_8() { return cBankAssignment_8; }

		//STRING
		public RuleCall getBankSTRINGTerminalRuleCall_8_0() { return cBankSTRINGTerminalRuleCall_8_0; }

		//"Verwendung"
		public Keyword getVerwendungKeyword_9() { return cVerwendungKeyword_9; }

		//verwendung=STRING
		public Assignment getVerwendungAssignment_10() { return cVerwendungAssignment_10; }

		//STRING
		public RuleCall getVerwendungSTRINGTerminalRuleCall_10_0() { return cVerwendungSTRINGTerminalRuleCall_10_0; }

		//"Inhaber"
		public Keyword getInhaberKeyword_11() { return cInhaberKeyword_11; }

		//inhaber=STRING
		public Assignment getInhaberAssignment_12() { return cInhaberAssignment_12; }

		//STRING
		public RuleCall getInhaberSTRINGTerminalRuleCall_12_0() { return cInhaberSTRINGTerminalRuleCall_12_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}

	public class BuchungsintervallElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Buchungsintervall");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBuchungsintervallKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameValidIDParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cIntervallAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cIntervallIntervallParserRuleCall_3_0 = (RuleCall)cIntervallAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Buchungsintervall:
		//
		//	"Buchungsintervall" name=ValidID "{" intervall=Intervall "}";
		public ParserRule getRule() { return rule; }

		//"Buchungsintervall" name=ValidID "{" intervall=Intervall "}"
		public Group getGroup() { return cGroup; }

		//"Buchungsintervall"
		public Keyword getBuchungsintervallKeyword_0() { return cBuchungsintervallKeyword_0; }

		//name=ValidID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ValidID
		public RuleCall getNameValidIDParserRuleCall_1_0() { return cNameValidIDParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//intervall=Intervall
		public Assignment getIntervallAssignment_3() { return cIntervallAssignment_3; }

		//Intervall
		public RuleCall getIntervallIntervallParserRuleCall_3_0() { return cIntervallIntervallParserRuleCall_3_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class IntervallElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Intervall");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cZumKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTagAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTagTAGTerminalRuleCall_1_0 = (RuleCall)cTagAssignment_1.eContents().get(0);
		private final Keyword cDerMonateKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cMonateAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cMonateMONATTerminalRuleCall_3_0 = (RuleCall)cMonateAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cMonateAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cMonateMONATTerminalRuleCall_4_1_0 = (RuleCall)cMonateAssignment_4_1.eContents().get(0);
		
		//Intervall:
		//
		//	"Zum" tag=TAG "der Monate" monate+=MONAT ("," monate+=MONAT)*;
		public ParserRule getRule() { return rule; }

		//"Zum" tag=TAG "der Monate" monate+=MONAT ("," monate+=MONAT)*
		public Group getGroup() { return cGroup; }

		//"Zum"
		public Keyword getZumKeyword_0() { return cZumKeyword_0; }

		//tag=TAG
		public Assignment getTagAssignment_1() { return cTagAssignment_1; }

		//TAG
		public RuleCall getTagTAGTerminalRuleCall_1_0() { return cTagTAGTerminalRuleCall_1_0; }

		//"der Monate"
		public Keyword getDerMonateKeyword_2() { return cDerMonateKeyword_2; }

		//monate+=MONAT
		public Assignment getMonateAssignment_3() { return cMonateAssignment_3; }

		//MONAT
		public RuleCall getMonateMONATTerminalRuleCall_3_0() { return cMonateMONATTerminalRuleCall_3_0; }

		//("," monate+=MONAT)*
		public Group getGroup_4() { return cGroup_4; }

		//","
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }

		//monate+=MONAT
		public Assignment getMonateAssignment_4_1() { return cMonateAssignment_4_1; }

		//MONAT
		public RuleCall getMonateMONATTerminalRuleCall_4_1_0() { return cMonateMONATTerminalRuleCall_4_1_0; }
	}

	public class KategorieElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Kategorie");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cKategorieKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameValidIDParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cBeschreibungAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cBeschreibungSTRINGTerminalRuleCall_2_1_0 = (RuleCall)cBeschreibungAssignment_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		
		//Kategorie:
		//
		//	"Kategorie" name=ValidID ("{" beschreibung=STRING "}")?;
		public ParserRule getRule() { return rule; }

		//"Kategorie" name=ValidID ("{" beschreibung=STRING "}")?
		public Group getGroup() { return cGroup; }

		//"Kategorie"
		public Keyword getKategorieKeyword_0() { return cKategorieKeyword_0; }

		//name=ValidID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ValidID
		public RuleCall getNameValidIDParserRuleCall_1_0() { return cNameValidIDParserRuleCall_1_0; }

		//("{" beschreibung=STRING "}")?
		public Group getGroup_2() { return cGroup_2; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2_0() { return cLeftCurlyBracketKeyword_2_0; }

		//beschreibung=STRING
		public Assignment getBeschreibungAssignment_2_1() { return cBeschreibungAssignment_2_1; }

		//STRING
		public RuleCall getBeschreibungSTRINGTerminalRuleCall_2_1_0() { return cBeschreibungSTRINGTerminalRuleCall_2_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_2_2() { return cRightCurlyBracketKeyword_2_2; }
	}

	public class BuchungElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Buchung");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cBuchungKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cNameAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cNameValidIDParserRuleCall_0_1_0 = (RuleCall)cNameAssignment_0_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Keyword cKontoKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final Assignment cKontoAssignment_0_4 = (Assignment)cGroup_0.eContents().get(4);
		private final CrossReference cKontoKontoCrossReference_0_4_0 = (CrossReference)cKontoAssignment_0_4.eContents().get(0);
		private final RuleCall cKontoKontoIDTerminalRuleCall_0_4_0_1 = (RuleCall)cKontoKontoCrossReference_0_4_0.eContents().get(1);
		private final Keyword cBetragKeyword_0_5 = (Keyword)cGroup_0.eContents().get(5);
		private final Assignment cBetragAssignment_0_6 = (Assignment)cGroup_0.eContents().get(6);
		private final RuleCall cBetragINTTerminalRuleCall_0_6_0 = (RuleCall)cBetragAssignment_0_6.eContents().get(0);
		private final Alternatives cAlternatives_0_7 = (Alternatives)cGroup_0.eContents().get(7);
		private final Group cGroup_0_7_0 = (Group)cAlternatives_0_7.eContents().get(0);
		private final Keyword cEmpf‰ngerKeyword_0_7_0_0 = (Keyword)cGroup_0_7_0.eContents().get(0);
		private final Assignment cEmpfaengerAssignment_0_7_0_1 = (Assignment)cGroup_0_7_0.eContents().get(1);
		private final CrossReference cEmpfaengerEmpfaengerCrossReference_0_7_0_1_0 = (CrossReference)cEmpfaengerAssignment_0_7_0_1.eContents().get(0);
		private final RuleCall cEmpfaengerEmpfaengerIDTerminalRuleCall_0_7_0_1_0_1 = (RuleCall)cEmpfaengerEmpfaengerCrossReference_0_7_0_1_0.eContents().get(1);
		private final Group cGroup_0_7_1 = (Group)cAlternatives_0_7.eContents().get(1);
		private final Keyword cVonKeyword_0_7_1_0 = (Keyword)cGroup_0_7_1.eContents().get(0);
		private final Assignment cVonAssignment_0_7_1_1 = (Assignment)cGroup_0_7_1.eContents().get(1);
		private final CrossReference cVonEmpfaengerCrossReference_0_7_1_1_0 = (CrossReference)cVonAssignment_0_7_1_1.eContents().get(0);
		private final RuleCall cVonEmpfaengerIDTerminalRuleCall_0_7_1_1_0_1 = (RuleCall)cVonEmpfaengerCrossReference_0_7_1_1_0.eContents().get(1);
		private final Keyword cIntervallKeyword_0_8 = (Keyword)cGroup_0.eContents().get(8);
		private final Assignment cIntervallAssignment_0_9 = (Assignment)cGroup_0.eContents().get(9);
		private final CrossReference cIntervallBuchungsintervallCrossReference_0_9_0 = (CrossReference)cIntervallAssignment_0_9.eContents().get(0);
		private final RuleCall cIntervallBuchungsintervallIDTerminalRuleCall_0_9_0_1 = (RuleCall)cIntervallBuchungsintervallCrossReference_0_9_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final RuleCall cIntervallParserRuleCall_1_0 = (RuleCall)cGroup_1.eContents().get(0);
		private final Keyword cKategorieKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cKategorieAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final CrossReference cKategorieKategorieCrossReference_1_2_0 = (CrossReference)cKategorieAssignment_1_2.eContents().get(0);
		private final RuleCall cKategorieKategorieIDTerminalRuleCall_1_2_0_1 = (RuleCall)cKategorieKategorieCrossReference_1_2_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		
		//Buchung:
		//
		//	"Buchung" name=ValidID "{" "Konto" konto=[Konto] "Betrag" betrag=INT ("Empf‰nger" empfaenger=[Empfaenger] | "von"
		//
		//	von=[Empfaenger]) "Intervall" intervall=[Buchungsintervall] | Intervall "Kategorie" kategorie+=[Kategorie] "}";
		public ParserRule getRule() { return rule; }

		//"Buchung" name=ValidID "{" "Konto" konto=[Konto] "Betrag" betrag=INT ("Empf‰nger" empfaenger=[Empfaenger] | "von"
		//
		//von=[Empfaenger]) "Intervall" intervall=[Buchungsintervall] | Intervall "Kategorie" kategorie+=[Kategorie] "}"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"Buchung" name=ValidID "{" "Konto" konto=[Konto] "Betrag" betrag=INT ("Empf‰nger" empfaenger=[Empfaenger] | "von"
		//
		//von=[Empfaenger]) "Intervall" intervall=[Buchungsintervall]
		public Group getGroup_0() { return cGroup_0; }

		//"Buchung"
		public Keyword getBuchungKeyword_0_0() { return cBuchungKeyword_0_0; }

		//name=ValidID
		public Assignment getNameAssignment_0_1() { return cNameAssignment_0_1; }

		//ValidID
		public RuleCall getNameValidIDParserRuleCall_0_1_0() { return cNameValidIDParserRuleCall_0_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_0_2() { return cLeftCurlyBracketKeyword_0_2; }

		//"Konto"
		public Keyword getKontoKeyword_0_3() { return cKontoKeyword_0_3; }

		//konto=[Konto]
		public Assignment getKontoAssignment_0_4() { return cKontoAssignment_0_4; }

		//[Konto]
		public CrossReference getKontoKontoCrossReference_0_4_0() { return cKontoKontoCrossReference_0_4_0; }

		//ID
		public RuleCall getKontoKontoIDTerminalRuleCall_0_4_0_1() { return cKontoKontoIDTerminalRuleCall_0_4_0_1; }

		//"Betrag"
		public Keyword getBetragKeyword_0_5() { return cBetragKeyword_0_5; }

		//betrag=INT
		public Assignment getBetragAssignment_0_6() { return cBetragAssignment_0_6; }

		//INT
		public RuleCall getBetragINTTerminalRuleCall_0_6_0() { return cBetragINTTerminalRuleCall_0_6_0; }

		//"Empf‰nger" empfaenger=[Empfaenger] | "von" von=[Empfaenger]
		public Alternatives getAlternatives_0_7() { return cAlternatives_0_7; }

		//"Empf‰nger" empfaenger=[Empfaenger]
		public Group getGroup_0_7_0() { return cGroup_0_7_0; }

		//"Empf‰nger"
		public Keyword getEmpf‰ngerKeyword_0_7_0_0() { return cEmpf‰ngerKeyword_0_7_0_0; }

		//empfaenger=[Empfaenger]
		public Assignment getEmpfaengerAssignment_0_7_0_1() { return cEmpfaengerAssignment_0_7_0_1; }

		//[Empfaenger]
		public CrossReference getEmpfaengerEmpfaengerCrossReference_0_7_0_1_0() { return cEmpfaengerEmpfaengerCrossReference_0_7_0_1_0; }

		//ID
		public RuleCall getEmpfaengerEmpfaengerIDTerminalRuleCall_0_7_0_1_0_1() { return cEmpfaengerEmpfaengerIDTerminalRuleCall_0_7_0_1_0_1; }

		//"von" von=[Empfaenger]
		public Group getGroup_0_7_1() { return cGroup_0_7_1; }

		//"von"
		public Keyword getVonKeyword_0_7_1_0() { return cVonKeyword_0_7_1_0; }

		//von=[Empfaenger]
		public Assignment getVonAssignment_0_7_1_1() { return cVonAssignment_0_7_1_1; }

		//[Empfaenger]
		public CrossReference getVonEmpfaengerCrossReference_0_7_1_1_0() { return cVonEmpfaengerCrossReference_0_7_1_1_0; }

		//ID
		public RuleCall getVonEmpfaengerIDTerminalRuleCall_0_7_1_1_0_1() { return cVonEmpfaengerIDTerminalRuleCall_0_7_1_1_0_1; }

		//"Intervall"
		public Keyword getIntervallKeyword_0_8() { return cIntervallKeyword_0_8; }

		//intervall=[Buchungsintervall]
		public Assignment getIntervallAssignment_0_9() { return cIntervallAssignment_0_9; }

		//[Buchungsintervall]
		public CrossReference getIntervallBuchungsintervallCrossReference_0_9_0() { return cIntervallBuchungsintervallCrossReference_0_9_0; }

		//ID
		public RuleCall getIntervallBuchungsintervallIDTerminalRuleCall_0_9_0_1() { return cIntervallBuchungsintervallIDTerminalRuleCall_0_9_0_1; }

		//Intervall "Kategorie" kategorie+=[Kategorie] "}"
		public Group getGroup_1() { return cGroup_1; }

		//Intervall
		public RuleCall getIntervallParserRuleCall_1_0() { return cIntervallParserRuleCall_1_0; }

		//"Kategorie"
		public Keyword getKategorieKeyword_1_1() { return cKategorieKeyword_1_1; }

		//kategorie+=[Kategorie]
		public Assignment getKategorieAssignment_1_2() { return cKategorieAssignment_1_2; }

		//[Kategorie]
		public CrossReference getKategorieKategorieCrossReference_1_2_0() { return cKategorieKategorieCrossReference_1_2_0; }

		//ID
		public RuleCall getKategorieKategorieIDTerminalRuleCall_1_2_0_1() { return cKategorieKategorieIDTerminalRuleCall_1_2_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_1_3() { return cRightCurlyBracketKeyword_1_3; }
	}

	public class EmpfaengerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Empfaenger");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEmpf‰ngerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameValidIDParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cStraEKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cStrasseAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cStrasseSTRINGTerminalRuleCall_2_2_0 = (RuleCall)cStrasseAssignment_2_2.eContents().get(0);
		private final Keyword cPLZKeyword_2_3 = (Keyword)cGroup_2.eContents().get(3);
		private final Assignment cPlzAssignment_2_4 = (Assignment)cGroup_2.eContents().get(4);
		private final RuleCall cPlzSTRINGTerminalRuleCall_2_4_0 = (RuleCall)cPlzAssignment_2_4.eContents().get(0);
		private final Keyword cOrtKeyword_2_5 = (Keyword)cGroup_2.eContents().get(5);
		private final Assignment cOrtAssignment_2_6 = (Assignment)cGroup_2.eContents().get(6);
		private final RuleCall cOrtSTRINGTerminalRuleCall_2_6_0 = (RuleCall)cOrtAssignment_2_6.eContents().get(0);
		private final Keyword cBemerkungKeyword_2_7 = (Keyword)cGroup_2.eContents().get(7);
		private final Assignment cBemerkungAssignment_2_8 = (Assignment)cGroup_2.eContents().get(8);
		private final RuleCall cBemerkungSTRINGTerminalRuleCall_2_8_0 = (RuleCall)cBemerkungAssignment_2_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_9 = (Keyword)cGroup_2.eContents().get(9);
		
		//Empfaenger:
		//
		//	"Empf‰nger" name=ValidID ("{" "Straﬂe" strasse=STRING "PLZ" plz=STRING "Ort" ort=STRING "Bemerkung" bemerkung=STRING
		//
		//	"}")?;
		public ParserRule getRule() { return rule; }

		//"Empf‰nger" name=ValidID ("{" "Straﬂe" strasse=STRING "PLZ" plz=STRING "Ort" ort=STRING "Bemerkung" bemerkung=STRING
		//
		//"}")?
		public Group getGroup() { return cGroup; }

		//"Empf‰nger"
		public Keyword getEmpf‰ngerKeyword_0() { return cEmpf‰ngerKeyword_0; }

		//name=ValidID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ValidID
		public RuleCall getNameValidIDParserRuleCall_1_0() { return cNameValidIDParserRuleCall_1_0; }

		//("{" "Straﬂe" strasse=STRING "PLZ" plz=STRING "Ort" ort=STRING "Bemerkung" bemerkung=STRING "}")?
		public Group getGroup_2() { return cGroup_2; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2_0() { return cLeftCurlyBracketKeyword_2_0; }

		//"Straﬂe"
		public Keyword getStraEKeyword_2_1() { return cStraEKeyword_2_1; }

		//strasse=STRING
		public Assignment getStrasseAssignment_2_2() { return cStrasseAssignment_2_2; }

		//STRING
		public RuleCall getStrasseSTRINGTerminalRuleCall_2_2_0() { return cStrasseSTRINGTerminalRuleCall_2_2_0; }

		//"PLZ"
		public Keyword getPLZKeyword_2_3() { return cPLZKeyword_2_3; }

		//plz=STRING
		public Assignment getPlzAssignment_2_4() { return cPlzAssignment_2_4; }

		//STRING
		public RuleCall getPlzSTRINGTerminalRuleCall_2_4_0() { return cPlzSTRINGTerminalRuleCall_2_4_0; }

		//"Ort"
		public Keyword getOrtKeyword_2_5() { return cOrtKeyword_2_5; }

		//ort=STRING
		public Assignment getOrtAssignment_2_6() { return cOrtAssignment_2_6; }

		//STRING
		public RuleCall getOrtSTRINGTerminalRuleCall_2_6_0() { return cOrtSTRINGTerminalRuleCall_2_6_0; }

		//"Bemerkung"
		public Keyword getBemerkungKeyword_2_7() { return cBemerkungKeyword_2_7; }

		//bemerkung=STRING
		public Assignment getBemerkungAssignment_2_8() { return cBemerkungAssignment_2_8; }

		//STRING
		public RuleCall getBemerkungSTRINGTerminalRuleCall_2_8_0() { return cBemerkungSTRINGTerminalRuleCall_2_8_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_2_9() { return cRightCurlyBracketKeyword_2_9; }
	}
	
	
	private FinModelFileElements pFinModelFile;
	private ImportElements pImport;
	private ElementElements pElement;
	private KontoElements pKonto;
	private TerminalRule tTAG;
	private TerminalRule tMONAT;
	private BuchungsintervallElements pBuchungsintervall;
	private IntervallElements pIntervall;
	private KategorieElements pKategorie;
	private BuchungElements pBuchung;
	private EmpfaengerElements pEmpfaenger;
	
	private final Grammar grammar;

	private XbaseGrammarAccess gaXbase;

	@Inject
	public FinGrammarAccess(GrammarProvider grammarProvider,
		XbaseGrammarAccess gaXbase) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaXbase = gaXbase;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.nie.fin.Fin".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public XbaseGrammarAccess getXbaseGrammarAccess() {
		return gaXbase;
	}

	
	//FinModelFile:
	//
	//	("package" name=QualifiedName)? imports+=Import* elements+=Element*;
	public FinModelFileElements getFinModelFileAccess() {
		return (pFinModelFile != null) ? pFinModelFile : (pFinModelFile = new FinModelFileElements());
	}
	
	public ParserRule getFinModelFileRule() {
		return getFinModelFileAccess().getRule();
	}

	//Import:
	//
	//	"import" importedNamespace=QualifiedName;
	public ImportElements getImportAccess() {
		return (pImport != null) ? pImport : (pImport = new ImportElements());
	}
	
	public ParserRule getImportRule() {
		return getImportAccess().getRule();
	}

	//Element:
	//
	//	Konto | Buchung | Empfaenger | Buchungsintervall | Kategorie;
	public ElementElements getElementAccess() {
		return (pElement != null) ? pElement : (pElement = new ElementElements());
	}
	
	public ParserRule getElementRule() {
		return getElementAccess().getRule();
	}

	//Konto:
	//
	//	"Konto" name=ValidID "{" "KtoNr" ktoNr=INT "Blz" blz=INT "Bank" bank=STRING "Verwendung" verwendung=STRING "Inhaber"
	//
	//	inhaber=STRING "}";
	public KontoElements getKontoAccess() {
		return (pKonto != null) ? pKonto : (pKonto = new KontoElements());
	}
	
	public ParserRule getKontoRule() {
		return getKontoAccess().getRule();
	}

	//terminal TAG:
	//
	//	"1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "10" | "11" | "12" | "13" | "14" | "15" | "16" | "17" | "18" |
	//
	//	"19" | "20" | "21" | "22" | "23" | "24" | "25" | "26" | "27" | "28" | "29" | "30" | "31";
	public TerminalRule getTAGRule() {
		return (tTAG != null) ? tTAG : (tTAG = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "TAG"));
	} 

	//terminal MONAT:
	//
	//	"Januar" | "Februar" | "M‰rz" | "April" | "Mai" | "Juni" | "Juli" | "August" | "September" | "Oktober" | "November" |
	//
	//	"Dezember";
	public TerminalRule getMONATRule() {
		return (tMONAT != null) ? tMONAT : (tMONAT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "MONAT"));
	} 

	//Buchungsintervall:
	//
	//	"Buchungsintervall" name=ValidID "{" intervall=Intervall "}";
	public BuchungsintervallElements getBuchungsintervallAccess() {
		return (pBuchungsintervall != null) ? pBuchungsintervall : (pBuchungsintervall = new BuchungsintervallElements());
	}
	
	public ParserRule getBuchungsintervallRule() {
		return getBuchungsintervallAccess().getRule();
	}

	//Intervall:
	//
	//	"Zum" tag=TAG "der Monate" monate+=MONAT ("," monate+=MONAT)*;
	public IntervallElements getIntervallAccess() {
		return (pIntervall != null) ? pIntervall : (pIntervall = new IntervallElements());
	}
	
	public ParserRule getIntervallRule() {
		return getIntervallAccess().getRule();
	}

	//Kategorie:
	//
	//	"Kategorie" name=ValidID ("{" beschreibung=STRING "}")?;
	public KategorieElements getKategorieAccess() {
		return (pKategorie != null) ? pKategorie : (pKategorie = new KategorieElements());
	}
	
	public ParserRule getKategorieRule() {
		return getKategorieAccess().getRule();
	}

	//Buchung:
	//
	//	"Buchung" name=ValidID "{" "Konto" konto=[Konto] "Betrag" betrag=INT ("Empf‰nger" empfaenger=[Empfaenger] | "von"
	//
	//	von=[Empfaenger]) "Intervall" intervall=[Buchungsintervall] | Intervall "Kategorie" kategorie+=[Kategorie] "}";
	public BuchungElements getBuchungAccess() {
		return (pBuchung != null) ? pBuchung : (pBuchung = new BuchungElements());
	}
	
	public ParserRule getBuchungRule() {
		return getBuchungAccess().getRule();
	}

	//Empfaenger:
	//
	//	"Empf‰nger" name=ValidID ("{" "Straﬂe" strasse=STRING "PLZ" plz=STRING "Ort" ort=STRING "Bemerkung" bemerkung=STRING
	//
	//	"}")?;
	public EmpfaengerElements getEmpfaengerAccess() {
		return (pEmpfaenger != null) ? pEmpfaenger : (pEmpfaenger = new EmpfaengerElements());
	}
	
	public ParserRule getEmpfaengerRule() {
		return getEmpfaengerAccess().getRule();
	}

	//XExpression:
	//
	//	XAssignment;
	public XbaseGrammarAccess.XExpressionElements getXExpressionAccess() {
		return gaXbase.getXExpressionAccess();
	}
	
	public ParserRule getXExpressionRule() {
		return getXExpressionAccess().getRule();
	}

	//XAssignment returns XExpression:
	//
	//	{XAssignment} / * (declaringType=[types::JvmDeclaredType] '::')? * / feature=[types::JvmIdentifiableElement|ValidID]
	//
	//	OpSingleAssign value=XAssignment | XOrExpression (=> ({XBinaryOperation.leftOperand=current}
	//
	//	feature=[types::JvmIdentifiableElement|OpMultiAssign]) rightOperand=XAssignment)?;
	public XbaseGrammarAccess.XAssignmentElements getXAssignmentAccess() {
		return gaXbase.getXAssignmentAccess();
	}
	
	public ParserRule getXAssignmentRule() {
		return getXAssignmentAccess().getRule();
	}

	//OpSingleAssign:
	//
	//	"=";
	public XbaseGrammarAccess.OpSingleAssignElements getOpSingleAssignAccess() {
		return gaXbase.getOpSingleAssignAccess();
	}
	
	public ParserRule getOpSingleAssignRule() {
		return getOpSingleAssignAccess().getRule();
	}

	//OpMultiAssign:
	//
	//	"+=";
	public XbaseGrammarAccess.OpMultiAssignElements getOpMultiAssignAccess() {
		return gaXbase.getOpMultiAssignAccess();
	}
	
	public ParserRule getOpMultiAssignRule() {
		return getOpMultiAssignAccess().getRule();
	}

	//XOrExpression returns XExpression:
	//
	//	XAndExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpOr])
	//
	//	rightOperand=XAndExpression)*;
	public XbaseGrammarAccess.XOrExpressionElements getXOrExpressionAccess() {
		return gaXbase.getXOrExpressionAccess();
	}
	
	public ParserRule getXOrExpressionRule() {
		return getXOrExpressionAccess().getRule();
	}

	//OpOr:
	//
	//	"||";
	public XbaseGrammarAccess.OpOrElements getOpOrAccess() {
		return gaXbase.getOpOrAccess();
	}
	
	public ParserRule getOpOrRule() {
		return getOpOrAccess().getRule();
	}

	//XAndExpression returns XExpression:
	//
	//	XEqualityExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpAnd])
	//
	//	rightOperand=XEqualityExpression)*;
	public XbaseGrammarAccess.XAndExpressionElements getXAndExpressionAccess() {
		return gaXbase.getXAndExpressionAccess();
	}
	
	public ParserRule getXAndExpressionRule() {
		return getXAndExpressionAccess().getRule();
	}

	//OpAnd:
	//
	//	"&&";
	public XbaseGrammarAccess.OpAndElements getOpAndAccess() {
		return gaXbase.getOpAndAccess();
	}
	
	public ParserRule getOpAndRule() {
		return getOpAndAccess().getRule();
	}

	//XEqualityExpression returns XExpression:
	//
	//	XRelationalExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpEquality])
	//
	//	rightOperand=XRelationalExpression)*;
	public XbaseGrammarAccess.XEqualityExpressionElements getXEqualityExpressionAccess() {
		return gaXbase.getXEqualityExpressionAccess();
	}
	
	public ParserRule getXEqualityExpressionRule() {
		return getXEqualityExpressionAccess().getRule();
	}

	//OpEquality:
	//
	//	"==" | "!=";
	public XbaseGrammarAccess.OpEqualityElements getOpEqualityAccess() {
		return gaXbase.getOpEqualityAccess();
	}
	
	public ParserRule getOpEqualityRule() {
		return getOpEqualityAccess().getRule();
	}

	//XRelationalExpression returns XExpression:
	//
	//	XOtherOperatorExpression (=> ({XInstanceOfExpression.expression=current} "instanceof") type=JvmTypeReference | =>
	//
	//	({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpCompare])
	//
	//	rightOperand=XOtherOperatorExpression)*;
	public XbaseGrammarAccess.XRelationalExpressionElements getXRelationalExpressionAccess() {
		return gaXbase.getXRelationalExpressionAccess();
	}
	
	public ParserRule getXRelationalExpressionRule() {
		return getXRelationalExpressionAccess().getRule();
	}

	//OpCompare:
	//
	//	">=" | "<=" | ">" | "<";
	public XbaseGrammarAccess.OpCompareElements getOpCompareAccess() {
		return gaXbase.getOpCompareAccess();
	}
	
	public ParserRule getOpCompareRule() {
		return getOpCompareAccess().getRule();
	}

	//XOtherOperatorExpression returns XExpression:
	//
	//	XAdditiveExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpOther])
	//
	//	rightOperand=XAdditiveExpression)*;
	public XbaseGrammarAccess.XOtherOperatorExpressionElements getXOtherOperatorExpressionAccess() {
		return gaXbase.getXOtherOperatorExpressionAccess();
	}
	
	public ParserRule getXOtherOperatorExpressionRule() {
		return getXOtherOperatorExpressionAccess().getRule();
	}

	//OpOther:
	//
	//	"->" | ".." | "=>" | ">" (=> (">" ">") | ">") | "<" (=> ("<" "<") | "<") | "<>" | "?:" | "<=>";
	public XbaseGrammarAccess.OpOtherElements getOpOtherAccess() {
		return gaXbase.getOpOtherAccess();
	}
	
	public ParserRule getOpOtherRule() {
		return getOpOtherAccess().getRule();
	}

	//XAdditiveExpression returns XExpression:
	//
	//	XMultiplicativeExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpAdd])
	//
	//	rightOperand=XMultiplicativeExpression)*;
	public XbaseGrammarAccess.XAdditiveExpressionElements getXAdditiveExpressionAccess() {
		return gaXbase.getXAdditiveExpressionAccess();
	}
	
	public ParserRule getXAdditiveExpressionRule() {
		return getXAdditiveExpressionAccess().getRule();
	}

	//OpAdd:
	//
	//	"+" | "-";
	public XbaseGrammarAccess.OpAddElements getOpAddAccess() {
		return gaXbase.getOpAddAccess();
	}
	
	public ParserRule getOpAddRule() {
		return getOpAddAccess().getRule();
	}

	//XMultiplicativeExpression returns XExpression:
	//
	//	XUnaryOperation (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpMulti])
	//
	//	rightOperand=XUnaryOperation)*;
	public XbaseGrammarAccess.XMultiplicativeExpressionElements getXMultiplicativeExpressionAccess() {
		return gaXbase.getXMultiplicativeExpressionAccess();
	}
	
	public ParserRule getXMultiplicativeExpressionRule() {
		return getXMultiplicativeExpressionAccess().getRule();
	}

	//OpMulti:
	//
	//	"*" | "**" | "/" | "%";
	public XbaseGrammarAccess.OpMultiElements getOpMultiAccess() {
		return gaXbase.getOpMultiAccess();
	}
	
	public ParserRule getOpMultiRule() {
		return getOpMultiAccess().getRule();
	}

	//XUnaryOperation returns XExpression:
	//
	//	{XUnaryOperation} feature=[types::JvmIdentifiableElement|OpUnary] operand=XCastedExpression | XCastedExpression;
	public XbaseGrammarAccess.XUnaryOperationElements getXUnaryOperationAccess() {
		return gaXbase.getXUnaryOperationAccess();
	}
	
	public ParserRule getXUnaryOperationRule() {
		return getXUnaryOperationAccess().getRule();
	}

	//OpUnary:
	//
	//	"!" | "-" | "+";
	public XbaseGrammarAccess.OpUnaryElements getOpUnaryAccess() {
		return gaXbase.getOpUnaryAccess();
	}
	
	public ParserRule getOpUnaryRule() {
		return getOpUnaryAccess().getRule();
	}

	//XCastedExpression returns XExpression:
	//
	//	XMemberFeatureCall (=> ({XCastedExpression.target=current} "as") type=JvmTypeReference)*;
	public XbaseGrammarAccess.XCastedExpressionElements getXCastedExpressionAccess() {
		return gaXbase.getXCastedExpressionAccess();
	}
	
	public ParserRule getXCastedExpressionRule() {
		return getXCastedExpressionAccess().getRule();
	}

	//XMemberFeatureCall returns XExpression:
	//
	//	XPrimaryExpression (=> ({XAssignment.assignable=current} "." feature=[types::JvmIdentifiableElement|ValidID]
	//
	//	OpSingleAssign) value=XAssignment | => ({XMemberFeatureCall.memberCallTarget=current} ("." | nullSafe?="?." |
	//
	//	spreading?="*.")) ("<" typeArguments+=JvmArgumentTypeReference ("," typeArguments+=JvmArgumentTypeReference)* ">")?
	//
	//	feature=[types::JvmIdentifiableElement|ValidID] (=> explicitOperationCall?="(" (memberCallArguments+=XShortClosure |
	//
	//	memberCallArguments+=XExpression ("," memberCallArguments+=XExpression)*)? ")")? memberCallArguments+=XClosure?)*;
	public XbaseGrammarAccess.XMemberFeatureCallElements getXMemberFeatureCallAccess() {
		return gaXbase.getXMemberFeatureCallAccess();
	}
	
	public ParserRule getXMemberFeatureCallRule() {
		return getXMemberFeatureCallAccess().getRule();
	}

	//XPrimaryExpression returns XExpression:
	//
	//	XConstructorCall | XBlockExpression | XSwitchExpression | XFeatureCall | XLiteral | XIfExpression |
	//
	//	XForLoopExpression | XWhileExpression | XDoWhileExpression | XThrowExpression | XReturnExpression |
	//
	//	XTryCatchFinallyExpression | XParenthesizedExpression;
	public XbaseGrammarAccess.XPrimaryExpressionElements getXPrimaryExpressionAccess() {
		return gaXbase.getXPrimaryExpressionAccess();
	}
	
	public ParserRule getXPrimaryExpressionRule() {
		return getXPrimaryExpressionAccess().getRule();
	}

	//XLiteral returns XExpression:
	//
	//	XClosure | XBooleanLiteral | XNumberLiteral | XNullLiteral | XStringLiteral | XTypeLiteral;
	public XbaseGrammarAccess.XLiteralElements getXLiteralAccess() {
		return gaXbase.getXLiteralAccess();
	}
	
	public ParserRule getXLiteralRule() {
		return getXLiteralAccess().getRule();
	}

	//XClosure returns XExpression:
	//
	//	=> ({XClosure} "[") => ((declaredFormalParameters+=JvmFormalParameter (","
	//
	//	declaredFormalParameters+=JvmFormalParameter)*)? explicitSyntax?="|")? expression=XExpressionInClosure "]";
	public XbaseGrammarAccess.XClosureElements getXClosureAccess() {
		return gaXbase.getXClosureAccess();
	}
	
	public ParserRule getXClosureRule() {
		return getXClosureAccess().getRule();
	}

	//XExpressionInClosure returns XExpression:
	//
	//	{XBlockExpression} (expressions+=XExpressionInsideBlock ";"?)*;
	public XbaseGrammarAccess.XExpressionInClosureElements getXExpressionInClosureAccess() {
		return gaXbase.getXExpressionInClosureAccess();
	}
	
	public ParserRule getXExpressionInClosureRule() {
		return getXExpressionInClosureAccess().getRule();
	}

	//XShortClosure returns XExpression:
	//
	//	=> ({XClosure} (declaredFormalParameters+=JvmFormalParameter ("," declaredFormalParameters+=JvmFormalParameter)*)?
	//
	//	explicitSyntax?="|") expression=XExpression;
	public XbaseGrammarAccess.XShortClosureElements getXShortClosureAccess() {
		return gaXbase.getXShortClosureAccess();
	}
	
	public ParserRule getXShortClosureRule() {
		return getXShortClosureAccess().getRule();
	}

	//XParenthesizedExpression returns XExpression:
	//
	//	"(" XExpression ")";
	public XbaseGrammarAccess.XParenthesizedExpressionElements getXParenthesizedExpressionAccess() {
		return gaXbase.getXParenthesizedExpressionAccess();
	}
	
	public ParserRule getXParenthesizedExpressionRule() {
		return getXParenthesizedExpressionAccess().getRule();
	}

	//XIfExpression returns XExpression:
	//
	//	{XIfExpression} "if" "(" if=XExpression ")" then=XExpression ("else" else=XExpression)?;
	public XbaseGrammarAccess.XIfExpressionElements getXIfExpressionAccess() {
		return gaXbase.getXIfExpressionAccess();
	}
	
	public ParserRule getXIfExpressionRule() {
		return getXIfExpressionAccess().getRule();
	}

	//XSwitchExpression returns XExpression:
	//
	//	{XSwitchExpression} "switch" (=> (localVarName=ValidID ":")? switch=XExpression | => ("(" localVarName=ValidID ":")
	//
	//	switch=XExpression ")") "{" cases+=XCasePart+ ("default" ":" default=XExpression)? "}";
	public XbaseGrammarAccess.XSwitchExpressionElements getXSwitchExpressionAccess() {
		return gaXbase.getXSwitchExpressionAccess();
	}
	
	public ParserRule getXSwitchExpressionRule() {
		return getXSwitchExpressionAccess().getRule();
	}

	//XCasePart:
	//
	//	typeGuard=JvmTypeReference? ("case" case=XExpression)? ":" then=XExpression;
	public XbaseGrammarAccess.XCasePartElements getXCasePartAccess() {
		return gaXbase.getXCasePartAccess();
	}
	
	public ParserRule getXCasePartRule() {
		return getXCasePartAccess().getRule();
	}

	//XForLoopExpression returns XExpression:
	//
	//	{XForLoopExpression} "for" "(" declaredParam=JvmFormalParameter ":" forExpression=XExpression ")"
	//
	//	eachExpression=XExpression;
	public XbaseGrammarAccess.XForLoopExpressionElements getXForLoopExpressionAccess() {
		return gaXbase.getXForLoopExpressionAccess();
	}
	
	public ParserRule getXForLoopExpressionRule() {
		return getXForLoopExpressionAccess().getRule();
	}

	//XWhileExpression returns XExpression:
	//
	//	{XWhileExpression} "while" "(" predicate=XExpression ")" body=XExpression;
	public XbaseGrammarAccess.XWhileExpressionElements getXWhileExpressionAccess() {
		return gaXbase.getXWhileExpressionAccess();
	}
	
	public ParserRule getXWhileExpressionRule() {
		return getXWhileExpressionAccess().getRule();
	}

	//XDoWhileExpression returns XExpression:
	//
	//	{XDoWhileExpression} "do" body=XExpression "while" "(" predicate=XExpression ")";
	public XbaseGrammarAccess.XDoWhileExpressionElements getXDoWhileExpressionAccess() {
		return gaXbase.getXDoWhileExpressionAccess();
	}
	
	public ParserRule getXDoWhileExpressionRule() {
		return getXDoWhileExpressionAccess().getRule();
	}

	//XBlockExpression returns XExpression:
	//
	//	{XBlockExpression} "{" (expressions+=XExpressionInsideBlock ";"?)* "}";
	public XbaseGrammarAccess.XBlockExpressionElements getXBlockExpressionAccess() {
		return gaXbase.getXBlockExpressionAccess();
	}
	
	public ParserRule getXBlockExpressionRule() {
		return getXBlockExpressionAccess().getRule();
	}

	//XExpressionInsideBlock returns XExpression:
	//
	//	XVariableDeclaration | XExpression;
	public XbaseGrammarAccess.XExpressionInsideBlockElements getXExpressionInsideBlockAccess() {
		return gaXbase.getXExpressionInsideBlockAccess();
	}
	
	public ParserRule getXExpressionInsideBlockRule() {
		return getXExpressionInsideBlockAccess().getRule();
	}

	//XVariableDeclaration returns XExpression:
	//
	//	{XVariableDeclaration} (writeable?="var" | "val") (=> (type=JvmTypeReference name=ValidID) | name=ValidID) ("="
	//
	//	right=XExpression)?;
	public XbaseGrammarAccess.XVariableDeclarationElements getXVariableDeclarationAccess() {
		return gaXbase.getXVariableDeclarationAccess();
	}
	
	public ParserRule getXVariableDeclarationRule() {
		return getXVariableDeclarationAccess().getRule();
	}

	//JvmFormalParameter returns types::JvmFormalParameter:
	//
	//	parameterType=JvmTypeReference? name=ValidID;
	public XbaseGrammarAccess.JvmFormalParameterElements getJvmFormalParameterAccess() {
		return gaXbase.getJvmFormalParameterAccess();
	}
	
	public ParserRule getJvmFormalParameterRule() {
		return getJvmFormalParameterAccess().getRule();
	}

	//FullJvmFormalParameter returns types::JvmFormalParameter:
	//
	//	parameterType=JvmTypeReference name=ValidID;
	public XbaseGrammarAccess.FullJvmFormalParameterElements getFullJvmFormalParameterAccess() {
		return gaXbase.getFullJvmFormalParameterAccess();
	}
	
	public ParserRule getFullJvmFormalParameterRule() {
		return getFullJvmFormalParameterAccess().getRule();
	}

	//XFeatureCall returns XExpression:
	//
	//	{XFeatureCall} declaringType=[types::JvmDeclaredType|StaticQualifier]? ("<" typeArguments+=JvmArgumentTypeReference
	//
	//	("," typeArguments+=JvmArgumentTypeReference)* ">")? feature=[types::JvmIdentifiableElement|IdOrSuper] (=>
	//
	//	explicitOperationCall?="(" (featureCallArguments+=XShortClosure | featureCallArguments+=XExpression (","
	//
	//	featureCallArguments+=XExpression)*)? ")")? featureCallArguments+=XClosure?;
	public XbaseGrammarAccess.XFeatureCallElements getXFeatureCallAccess() {
		return gaXbase.getXFeatureCallAccess();
	}
	
	public ParserRule getXFeatureCallRule() {
		return getXFeatureCallAccess().getRule();
	}

	//IdOrSuper:
	//
	//	ValidID | "super";
	public XbaseGrammarAccess.IdOrSuperElements getIdOrSuperAccess() {
		return gaXbase.getIdOrSuperAccess();
	}
	
	public ParserRule getIdOrSuperRule() {
		return getIdOrSuperAccess().getRule();
	}

	//// This is a workaround since ANTLR will not be able to resolve
	//
	//
	//// StaticQualifier: ValidID ('::' ValidID)*; and XFeatureCall: (StaticQualifier '::')? ValidID
	//
	//
	//// Make sure to change the value converter if you change the syntax of the StaticQualifier
	// StaticQualifier:
	//
	//	(ValidID "::")+;
	public XbaseGrammarAccess.StaticQualifierElements getStaticQualifierAccess() {
		return gaXbase.getStaticQualifierAccess();
	}
	
	public ParserRule getStaticQualifierRule() {
		return getStaticQualifierAccess().getRule();
	}

	//XConstructorCall returns XExpression:
	//
	//	{XConstructorCall} "new" constructor=[types::JvmConstructor|QualifiedName] ("<"
	//
	//	typeArguments+=JvmArgumentTypeReference ("," typeArguments+=JvmArgumentTypeReference)* ">")? ("("
	//
	//	(arguments+=XShortClosure | arguments+=XExpression ("," arguments+=XExpression)*)? ")")? arguments+=XClosure?;
	public XbaseGrammarAccess.XConstructorCallElements getXConstructorCallAccess() {
		return gaXbase.getXConstructorCallAccess();
	}
	
	public ParserRule getXConstructorCallRule() {
		return getXConstructorCallAccess().getRule();
	}

	//XBooleanLiteral returns XExpression:
	//
	//	{XBooleanLiteral} ("false" | isTrue?="true");
	public XbaseGrammarAccess.XBooleanLiteralElements getXBooleanLiteralAccess() {
		return gaXbase.getXBooleanLiteralAccess();
	}
	
	public ParserRule getXBooleanLiteralRule() {
		return getXBooleanLiteralAccess().getRule();
	}

	//XNullLiteral returns XExpression:
	//
	//	{XNullLiteral} "null";
	public XbaseGrammarAccess.XNullLiteralElements getXNullLiteralAccess() {
		return gaXbase.getXNullLiteralAccess();
	}
	
	public ParserRule getXNullLiteralRule() {
		return getXNullLiteralAccess().getRule();
	}

	//XNumberLiteral returns XExpression:
	//
	//	{XNumberLiteral} value=Number;
	public XbaseGrammarAccess.XNumberLiteralElements getXNumberLiteralAccess() {
		return gaXbase.getXNumberLiteralAccess();
	}
	
	public ParserRule getXNumberLiteralRule() {
		return getXNumberLiteralAccess().getRule();
	}

	//XStringLiteral returns XExpression:
	//
	//	{XStringLiteral} value=STRING;
	public XbaseGrammarAccess.XStringLiteralElements getXStringLiteralAccess() {
		return gaXbase.getXStringLiteralAccess();
	}
	
	public ParserRule getXStringLiteralRule() {
		return getXStringLiteralAccess().getRule();
	}

	//XTypeLiteral returns XExpression:
	//
	//	{XTypeLiteral} "typeof" "(" type=[types::JvmType|QualifiedName] ")";
	public XbaseGrammarAccess.XTypeLiteralElements getXTypeLiteralAccess() {
		return gaXbase.getXTypeLiteralAccess();
	}
	
	public ParserRule getXTypeLiteralRule() {
		return getXTypeLiteralAccess().getRule();
	}

	//XThrowExpression returns XExpression:
	//
	//	{XThrowExpression} "throw" expression=XExpression;
	public XbaseGrammarAccess.XThrowExpressionElements getXThrowExpressionAccess() {
		return gaXbase.getXThrowExpressionAccess();
	}
	
	public ParserRule getXThrowExpressionRule() {
		return getXThrowExpressionAccess().getRule();
	}

	//XReturnExpression returns XExpression:
	//
	//	{XReturnExpression} "return" => expression=XExpression?;
	public XbaseGrammarAccess.XReturnExpressionElements getXReturnExpressionAccess() {
		return gaXbase.getXReturnExpressionAccess();
	}
	
	public ParserRule getXReturnExpressionRule() {
		return getXReturnExpressionAccess().getRule();
	}

	//XTryCatchFinallyExpression returns XExpression:
	//
	//	{XTryCatchFinallyExpression} "try" expression=XExpression (catchClauses+=XCatchClause+ ("finally"
	//
	//	finallyExpression=XExpression)? | "finally" finallyExpression=XExpression);
	public XbaseGrammarAccess.XTryCatchFinallyExpressionElements getXTryCatchFinallyExpressionAccess() {
		return gaXbase.getXTryCatchFinallyExpressionAccess();
	}
	
	public ParserRule getXTryCatchFinallyExpressionRule() {
		return getXTryCatchFinallyExpressionAccess().getRule();
	}

	//XCatchClause:
	//
	//	"catch" "(" declaredParam=FullJvmFormalParameter ")" expression=XExpression;
	public XbaseGrammarAccess.XCatchClauseElements getXCatchClauseAccess() {
		return gaXbase.getXCatchClauseAccess();
	}
	
	public ParserRule getXCatchClauseRule() {
		return getXCatchClauseAccess().getRule();
	}

	//QualifiedName:
	//
	//	ValidID ("." ValidID)*;
	public XbaseGrammarAccess.QualifiedNameElements getQualifiedNameAccess() {
		return gaXbase.getQualifiedNameAccess();
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//Number hidden():
	//
	//	HEX | (INT | DECIMAL) ("." (INT | DECIMAL))?;
	public XbaseGrammarAccess.NumberElements getNumberAccess() {
		return gaXbase.getNumberAccess();
	}
	
	public ParserRule getNumberRule() {
		return getNumberAccess().getRule();
	}

	//terminal HEX:
	//
	//	("0x" | "0X") ("0".."9" | "a".."f" | "A".."F" | "_")+ ("#" (("b" | "B") ("i" | "I") | ("l" | "L")))?;
	public TerminalRule getHEXRule() {
		return gaXbase.getHEXRule();
	} 

	//terminal INT returns ecore::EInt:
	//
	//	"0".."9" ("0".."9" | "_")*;
	public TerminalRule getINTRule() {
		return gaXbase.getINTRule();
	} 

	//terminal DECIMAL:
	//
	//	INT (("e" | "E") ("+" | "-")? INT)? (("b" | "B") ("i" | "I" | "d" | "D") | ("l" | "L" | "d" | "D" | "f" | "F"))?;
	public TerminalRule getDECIMALRule() {
		return gaXbase.getDECIMALRule();
	} 

	//JvmTypeReference:
	//
	//	JvmParameterizedTypeReference => ({JvmGenericArrayTypeReference.componentType=current} "[" "]")* | XFunctionTypeRef;
	public XtypeGrammarAccess.JvmTypeReferenceElements getJvmTypeReferenceAccess() {
		return gaXbase.getJvmTypeReferenceAccess();
	}
	
	public ParserRule getJvmTypeReferenceRule() {
		return getJvmTypeReferenceAccess().getRule();
	}

	//XFunctionTypeRef:
	//
	//	("(" (paramTypes+=JvmTypeReference ("," paramTypes+=JvmTypeReference)*)? ")")? "=>" returnType=JvmTypeReference;
	public XtypeGrammarAccess.XFunctionTypeRefElements getXFunctionTypeRefAccess() {
		return gaXbase.getXFunctionTypeRefAccess();
	}
	
	public ParserRule getXFunctionTypeRefRule() {
		return getXFunctionTypeRefAccess().getRule();
	}

	//JvmParameterizedTypeReference:
	//
	//	type=[JvmType|QualifiedName] ("<" arguments+=JvmArgumentTypeReference ("," arguments+=JvmArgumentTypeReference)*
	//
	//	">")?;
	public XtypeGrammarAccess.JvmParameterizedTypeReferenceElements getJvmParameterizedTypeReferenceAccess() {
		return gaXbase.getJvmParameterizedTypeReferenceAccess();
	}
	
	public ParserRule getJvmParameterizedTypeReferenceRule() {
		return getJvmParameterizedTypeReferenceAccess().getRule();
	}

	//JvmArgumentTypeReference returns JvmTypeReference:
	//
	//	JvmTypeReference | JvmWildcardTypeReference;
	public XtypeGrammarAccess.JvmArgumentTypeReferenceElements getJvmArgumentTypeReferenceAccess() {
		return gaXbase.getJvmArgumentTypeReferenceAccess();
	}
	
	public ParserRule getJvmArgumentTypeReferenceRule() {
		return getJvmArgumentTypeReferenceAccess().getRule();
	}

	//JvmWildcardTypeReference:
	//
	//	{JvmWildcardTypeReference} "?" (constraints+=JvmUpperBound | constraints+=JvmLowerBound)?;
	public XtypeGrammarAccess.JvmWildcardTypeReferenceElements getJvmWildcardTypeReferenceAccess() {
		return gaXbase.getJvmWildcardTypeReferenceAccess();
	}
	
	public ParserRule getJvmWildcardTypeReferenceRule() {
		return getJvmWildcardTypeReferenceAccess().getRule();
	}

	//JvmUpperBound:
	//
	//	"extends" typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmUpperBoundElements getJvmUpperBoundAccess() {
		return gaXbase.getJvmUpperBoundAccess();
	}
	
	public ParserRule getJvmUpperBoundRule() {
		return getJvmUpperBoundAccess().getRule();
	}

	//JvmUpperBoundAnded returns JvmUpperBound:
	//
	//	"&" typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmUpperBoundAndedElements getJvmUpperBoundAndedAccess() {
		return gaXbase.getJvmUpperBoundAndedAccess();
	}
	
	public ParserRule getJvmUpperBoundAndedRule() {
		return getJvmUpperBoundAndedAccess().getRule();
	}

	//JvmLowerBound:
	//
	//	"super" typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmLowerBoundElements getJvmLowerBoundAccess() {
		return gaXbase.getJvmLowerBoundAccess();
	}
	
	public ParserRule getJvmLowerBoundRule() {
		return getJvmLowerBoundAccess().getRule();
	}

	//JvmTypeParameter:
	//
	//	name=ValidID (constraints+=JvmUpperBound constraints+=JvmUpperBoundAnded* | constraints+=JvmLowerBound)?;
	public XtypeGrammarAccess.JvmTypeParameterElements getJvmTypeParameterAccess() {
		return gaXbase.getJvmTypeParameterAccess();
	}
	
	public ParserRule getJvmTypeParameterRule() {
		return getJvmTypeParameterAccess().getRule();
	}

	//ValidID:
	//
	//	ID;
	public XtypeGrammarAccess.ValidIDElements getValidIDAccess() {
		return gaXbase.getValidIDAccess();
	}
	
	public ParserRule getValidIDRule() {
		return getValidIDAccess().getRule();
	}

	//terminal ID:
	//
	//	"^"? ("a".."z" | "A".."Z" | "$" | "_") ("a".."z" | "A".."Z" | "$" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaXbase.getIDRule();
	} 

	//terminal STRING:
	//
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaXbase.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaXbase.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaXbase.getSL_COMMENTRule();
	} 

	//terminal WS:
	//
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaXbase.getWSRule();
	} 

	//terminal ANY_OTHER:
	//
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaXbase.getANY_OTHERRule();
	} 
}
