/*
* generated by Xtext
*/

package de.nie.fin.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.xbase.services.XbaseGrammarAccess;
import org.eclipse.xtext.xbase.services.XtypeGrammarAccess;

@Singleton
public class FinGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class FinModelFileElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FinModelFile");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Keyword cPackageKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cNameAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cNameQualifiedNameParserRuleCall_0_1_0 = (RuleCall)cNameAssignment_0_1.eContents().get(0);
		private final Assignment cImportsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cImportsImportParserRuleCall_1_0 = (RuleCall)cImportsAssignment_1.eContents().get(0);
		private final Assignment cElementsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cElementsElementParserRuleCall_2_0 = (RuleCall)cElementsAssignment_2.eContents().get(0);
		
		//FinModelFile:
		//
		//	("package" name=QualifiedName)? imports+=Import* elements+=Element*;
		public ParserRule getRule() { return rule; }

		//("package" name=QualifiedName)? imports+=Import* elements+=Element*
		public Group getGroup() { return cGroup; }

		//("package" name=QualifiedName)?
		public Group getGroup_0() { return cGroup_0; }

		//"package"
		public Keyword getPackageKeyword_0_0() { return cPackageKeyword_0_0; }

		//name=QualifiedName
		public Assignment getNameAssignment_0_1() { return cNameAssignment_0_1; }

		//QualifiedName
		public RuleCall getNameQualifiedNameParserRuleCall_0_1_0() { return cNameQualifiedNameParserRuleCall_0_1_0; }

		//imports+=Import*
		public Assignment getImportsAssignment_1() { return cImportsAssignment_1; }

		//Import
		public RuleCall getImportsImportParserRuleCall_1_0() { return cImportsImportParserRuleCall_1_0; }

		//elements+=Element*
		public Assignment getElementsAssignment_2() { return cElementsAssignment_2; }

		//Element
		public RuleCall getElementsElementParserRuleCall_2_0() { return cElementsElementParserRuleCall_2_0; }
	}

	public class ElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Element");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cKontoParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cBuchungParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cKontaktParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cBuchungsintervallParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cKategorieParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//Element:
		//
		//	Konto | Buchung | Kontakt | Buchungsintervall | Kategorie;
		public ParserRule getRule() { return rule; }

		//Konto | Buchung | Kontakt | Buchungsintervall | Kategorie
		public Alternatives getAlternatives() { return cAlternatives; }

		//Konto
		public RuleCall getKontoParserRuleCall_0() { return cKontoParserRuleCall_0; }

		//Buchung
		public RuleCall getBuchungParserRuleCall_1() { return cBuchungParserRuleCall_1; }

		//Kontakt
		public RuleCall getKontaktParserRuleCall_2() { return cKontaktParserRuleCall_2; }

		//Buchungsintervall
		public RuleCall getBuchungsintervallParserRuleCall_3() { return cBuchungsintervallParserRuleCall_3; }

		//Kategorie
		public RuleCall getKategorieParserRuleCall_4() { return cKategorieParserRuleCall_4; }
	}

	public class ImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Import");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cImportKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cImportedNamespaceAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cImportedNamespaceQualifiedNameParserRuleCall_1_0 = (RuleCall)cImportedNamespaceAssignment_1.eContents().get(0);
		
		//Import:
		//
		//	"import" importedNamespace=QualifiedName;
		public ParserRule getRule() { return rule; }

		//"import" importedNamespace=QualifiedName
		public Group getGroup() { return cGroup; }

		//"import"
		public Keyword getImportKeyword_0() { return cImportKeyword_0; }

		//importedNamespace=QualifiedName
		public Assignment getImportedNamespaceAssignment_1() { return cImportedNamespaceAssignment_1; }

		//QualifiedName
		public RuleCall getImportedNamespaceQualifiedNameParserRuleCall_1_0() { return cImportedNamespaceQualifiedNameParserRuleCall_1_0; }
	}

	public class KontoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Konto");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cKontoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameValidIDParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cKtoNrKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cKtoNrAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cKtoNrINTTerminalRuleCall_4_0 = (RuleCall)cKtoNrAssignment_4.eContents().get(0);
		private final Keyword cBlzKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cBlzAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cBlzINTTerminalRuleCall_6_0 = (RuleCall)cBlzAssignment_6.eContents().get(0);
		private final Keyword cBankKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cBankAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cBankKontaktCrossReference_8_0 = (CrossReference)cBankAssignment_8.eContents().get(0);
		private final RuleCall cBankKontaktIDTerminalRuleCall_8_0_1 = (RuleCall)cBankKontaktCrossReference_8_0.eContents().get(1);
		private final Keyword cVerwendungKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cVerwendungAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cVerwendungSTRINGTerminalRuleCall_10_0 = (RuleCall)cVerwendungAssignment_10.eContents().get(0);
		private final Keyword cInhaberKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cInhaberAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final CrossReference cInhaberKontaktCrossReference_12_0 = (CrossReference)cInhaberAssignment_12.eContents().get(0);
		private final RuleCall cInhaberKontaktIDTerminalRuleCall_12_0_1 = (RuleCall)cInhaberKontaktCrossReference_12_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Konto:
		//
		//	"Konto" name=ValidID "{" "KtoNr" ktoNr=INT "Blz" blz=INT "Bank" bank=[Kontakt] "Verwendung" verwendung=STRING
		//
		//	"Inhaber" inhaber=[Kontakt] "}";
		public ParserRule getRule() { return rule; }

		//"Konto" name=ValidID "{" "KtoNr" ktoNr=INT "Blz" blz=INT "Bank" bank=[Kontakt] "Verwendung" verwendung=STRING "Inhaber"
		//
		//inhaber=[Kontakt] "}"
		public Group getGroup() { return cGroup; }

		//"Konto"
		public Keyword getKontoKeyword_0() { return cKontoKeyword_0; }

		//name=ValidID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ValidID
		public RuleCall getNameValidIDParserRuleCall_1_0() { return cNameValidIDParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"KtoNr"
		public Keyword getKtoNrKeyword_3() { return cKtoNrKeyword_3; }

		//ktoNr=INT
		public Assignment getKtoNrAssignment_4() { return cKtoNrAssignment_4; }

		//INT
		public RuleCall getKtoNrINTTerminalRuleCall_4_0() { return cKtoNrINTTerminalRuleCall_4_0; }

		//"Blz"
		public Keyword getBlzKeyword_5() { return cBlzKeyword_5; }

		//blz=INT
		public Assignment getBlzAssignment_6() { return cBlzAssignment_6; }

		//INT
		public RuleCall getBlzINTTerminalRuleCall_6_0() { return cBlzINTTerminalRuleCall_6_0; }

		//"Bank"
		public Keyword getBankKeyword_7() { return cBankKeyword_7; }

		//bank=[Kontakt]
		public Assignment getBankAssignment_8() { return cBankAssignment_8; }

		//[Kontakt]
		public CrossReference getBankKontaktCrossReference_8_0() { return cBankKontaktCrossReference_8_0; }

		//ID
		public RuleCall getBankKontaktIDTerminalRuleCall_8_0_1() { return cBankKontaktIDTerminalRuleCall_8_0_1; }

		//"Verwendung"
		public Keyword getVerwendungKeyword_9() { return cVerwendungKeyword_9; }

		//verwendung=STRING
		public Assignment getVerwendungAssignment_10() { return cVerwendungAssignment_10; }

		//STRING
		public RuleCall getVerwendungSTRINGTerminalRuleCall_10_0() { return cVerwendungSTRINGTerminalRuleCall_10_0; }

		//"Inhaber"
		public Keyword getInhaberKeyword_11() { return cInhaberKeyword_11; }

		//inhaber=[Kontakt]
		public Assignment getInhaberAssignment_12() { return cInhaberAssignment_12; }

		//[Kontakt]
		public CrossReference getInhaberKontaktCrossReference_12_0() { return cInhaberKontaktCrossReference_12_0; }

		//ID
		public RuleCall getInhaberKontaktIDTerminalRuleCall_12_0_1() { return cInhaberKontaktIDTerminalRuleCall_12_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}

	public class BuchungsintervallElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Buchungsintervall");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBuchungsintervallKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameValidIDParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cIntervallAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cIntervallIntervallParserRuleCall_3_0 = (RuleCall)cIntervallAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Buchungsintervall:
		//
		//	"Buchungsintervall" name=ValidID "{" intervall=Intervall "}";
		public ParserRule getRule() { return rule; }

		//"Buchungsintervall" name=ValidID "{" intervall=Intervall "}"
		public Group getGroup() { return cGroup; }

		//"Buchungsintervall"
		public Keyword getBuchungsintervallKeyword_0() { return cBuchungsintervallKeyword_0; }

		//name=ValidID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ValidID
		public RuleCall getNameValidIDParserRuleCall_1_0() { return cNameValidIDParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//intervall=Intervall
		public Assignment getIntervallAssignment_3() { return cIntervallAssignment_3; }

		//Intervall
		public RuleCall getIntervallIntervallParserRuleCall_3_0() { return cIntervallIntervallParserRuleCall_3_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class IntervallElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Intervall");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cZumKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTagAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTagTAGTerminalRuleCall_1_0 = (RuleCall)cTagAssignment_1.eContents().get(0);
		private final Keyword cDerMonateKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Assignment cMonateAssignment_3_0 = (Assignment)cGroup_3.eContents().get(0);
		private final RuleCall cMonateMONATEnumRuleCall_3_0_0 = (RuleCall)cMonateAssignment_3_0.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cGroup_3.eContents().get(1);
		private final Keyword cCommaKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Assignment cMonateAssignment_3_1_1 = (Assignment)cGroup_3_1.eContents().get(1);
		private final RuleCall cMonateMONATEnumRuleCall_3_1_1_0 = (RuleCall)cMonateAssignment_3_1_1.eContents().get(0);
		
		//Intervall:
		//
		//	"Zum" tag=TAG "der Monate" (monate+=MONAT ("," monate+=MONAT)*);
		public ParserRule getRule() { return rule; }

		//"Zum" tag=TAG "der Monate" (monate+=MONAT ("," monate+=MONAT)*)
		public Group getGroup() { return cGroup; }

		//"Zum"
		public Keyword getZumKeyword_0() { return cZumKeyword_0; }

		//tag=TAG
		public Assignment getTagAssignment_1() { return cTagAssignment_1; }

		//TAG
		public RuleCall getTagTAGTerminalRuleCall_1_0() { return cTagTAGTerminalRuleCall_1_0; }

		//"der Monate"
		public Keyword getDerMonateKeyword_2() { return cDerMonateKeyword_2; }

		//monate+=MONAT ("," monate+=MONAT)*
		public Group getGroup_3() { return cGroup_3; }

		//monate+=MONAT
		public Assignment getMonateAssignment_3_0() { return cMonateAssignment_3_0; }

		//MONAT
		public RuleCall getMonateMONATEnumRuleCall_3_0_0() { return cMonateMONATEnumRuleCall_3_0_0; }

		//("," monate+=MONAT)*
		public Group getGroup_3_1() { return cGroup_3_1; }

		//","
		public Keyword getCommaKeyword_3_1_0() { return cCommaKeyword_3_1_0; }

		//monate+=MONAT
		public Assignment getMonateAssignment_3_1_1() { return cMonateAssignment_3_1_1; }

		//MONAT
		public RuleCall getMonateMONATEnumRuleCall_3_1_1_0() { return cMonateMONATEnumRuleCall_3_1_1_0; }
	}

	public class KategorieElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Kategorie");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cKategorieKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameValidIDParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Kategorie:
		//
		//	"Kategorie" name=ValidID;
		public ParserRule getRule() { return rule; }

		//"Kategorie" name=ValidID
		public Group getGroup() { return cGroup; }

		//"Kategorie"
		public Keyword getKategorieKeyword_0() { return cKategorieKeyword_0; }

		//name=ValidID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ValidID
		public RuleCall getNameValidIDParserRuleCall_1_0() { return cNameValidIDParserRuleCall_1_0; }
	}

	public class BuchungElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Buchung");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBuchungKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameValidIDParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cKontoKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cKontoAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cKontoKontoCrossReference_4_0 = (CrossReference)cKontoAssignment_4.eContents().get(0);
		private final RuleCall cKontoKontoIDTerminalRuleCall_4_0_1 = (RuleCall)cKontoKontoCrossReference_4_0.eContents().get(1);
		private final Keyword cBetragKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cBetragAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cBetragINTTerminalRuleCall_6_0 = (RuleCall)cBetragAssignment_6.eContents().get(0);
		private final Alternatives cAlternatives_7 = (Alternatives)cGroup.eContents().get(7);
		private final Group cGroup_7_0 = (Group)cAlternatives_7.eContents().get(0);
		private final Keyword cEmpf‰ngerKeyword_7_0_0 = (Keyword)cGroup_7_0.eContents().get(0);
		private final Assignment cEmpfaengerAssignment_7_0_1 = (Assignment)cGroup_7_0.eContents().get(1);
		private final CrossReference cEmpfaengerKontaktCrossReference_7_0_1_0 = (CrossReference)cEmpfaengerAssignment_7_0_1.eContents().get(0);
		private final RuleCall cEmpfaengerKontaktIDTerminalRuleCall_7_0_1_0_1 = (RuleCall)cEmpfaengerKontaktCrossReference_7_0_1_0.eContents().get(1);
		private final Group cGroup_7_0_2 = (Group)cGroup_7_0.eContents().get(2);
		private final Keyword cEmpf‰ngerKontoKeyword_7_0_2_0 = (Keyword)cGroup_7_0_2.eContents().get(0);
		private final Assignment cEmpfaengerKtoAssignment_7_0_2_1 = (Assignment)cGroup_7_0_2.eContents().get(1);
		private final CrossReference cEmpfaengerKtoKontoCrossReference_7_0_2_1_0 = (CrossReference)cEmpfaengerKtoAssignment_7_0_2_1.eContents().get(0);
		private final RuleCall cEmpfaengerKtoKontoIDTerminalRuleCall_7_0_2_1_0_1 = (RuleCall)cEmpfaengerKtoKontoCrossReference_7_0_2_1_0.eContents().get(1);
		private final Group cGroup_7_1 = (Group)cAlternatives_7.eContents().get(1);
		private final Keyword cVonKeyword_7_1_0 = (Keyword)cGroup_7_1.eContents().get(0);
		private final Assignment cVonAssignment_7_1_1 = (Assignment)cGroup_7_1.eContents().get(1);
		private final CrossReference cVonKontaktCrossReference_7_1_1_0 = (CrossReference)cVonAssignment_7_1_1.eContents().get(0);
		private final RuleCall cVonKontaktIDTerminalRuleCall_7_1_1_0_1 = (RuleCall)cVonKontaktCrossReference_7_1_1_0.eContents().get(1);
		private final Group cGroup_7_1_2 = (Group)cGroup_7_1.eContents().get(2);
		private final Keyword cKontoKeyword_7_1_2_0 = (Keyword)cGroup_7_1_2.eContents().get(0);
		private final Assignment cVonKtoAssignment_7_1_2_1 = (Assignment)cGroup_7_1_2.eContents().get(1);
		private final CrossReference cVonKtoKontoCrossReference_7_1_2_1_0 = (CrossReference)cVonKtoAssignment_7_1_2_1.eContents().get(0);
		private final RuleCall cVonKtoKontoIDTerminalRuleCall_7_1_2_1_0_1 = (RuleCall)cVonKtoKontoCrossReference_7_1_2_1_0.eContents().get(1);
		private final Alternatives cAlternatives_8 = (Alternatives)cGroup.eContents().get(8);
		private final Group cGroup_8_0 = (Group)cAlternatives_8.eContents().get(0);
		private final Keyword cIntervallKeyword_8_0_0 = (Keyword)cGroup_8_0.eContents().get(0);
		private final Assignment cIntervallAssignment_8_0_1 = (Assignment)cGroup_8_0.eContents().get(1);
		private final RuleCall cIntervallIntervallParserRuleCall_8_0_1_0 = (RuleCall)cIntervallAssignment_8_0_1.eContents().get(0);
		private final Group cGroup_8_1 = (Group)cAlternatives_8.eContents().get(1);
		private final Keyword cIntervallKeyword_8_1_0 = (Keyword)cGroup_8_1.eContents().get(0);
		private final Assignment cBuchIntervAssignment_8_1_1 = (Assignment)cGroup_8_1.eContents().get(1);
		private final CrossReference cBuchIntervBuchungsintervallCrossReference_8_1_1_0 = (CrossReference)cBuchIntervAssignment_8_1_1.eContents().get(0);
		private final RuleCall cBuchIntervBuchungsintervallIDTerminalRuleCall_8_1_1_0_1 = (RuleCall)cBuchIntervBuchungsintervallCrossReference_8_1_1_0.eContents().get(1);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cKategorieKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cKategorieAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final CrossReference cKategorieKategorieCrossReference_9_1_0 = (CrossReference)cKategorieAssignment_9_1.eContents().get(0);
		private final RuleCall cKategorieKategorieIDTerminalRuleCall_9_1_0_1 = (RuleCall)cKategorieKategorieCrossReference_9_1_0.eContents().get(1);
		private final Group cGroup_9_2 = (Group)cGroup_9.eContents().get(2);
		private final Keyword cCommaKeyword_9_2_0 = (Keyword)cGroup_9_2.eContents().get(0);
		private final Assignment cKategorieAssignment_9_2_1 = (Assignment)cGroup_9_2.eContents().get(1);
		private final CrossReference cKategorieKategorieCrossReference_9_2_1_0 = (CrossReference)cKategorieAssignment_9_2_1.eContents().get(0);
		private final RuleCall cKategorieKategorieIDTerminalRuleCall_9_2_1_0_1 = (RuleCall)cKategorieKategorieCrossReference_9_2_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Buchung:
		//
		//	"Buchung" name=ValidID "{" "Konto" konto=[Konto] "Betrag" betrag=INT ("Empf‰nger" empfaenger=[Kontakt]
		//
		//	("Empf‰ngerKonto" empfaengerKto=[Konto])? | "von" von=[Kontakt] ("Konto" vonKto=[Konto])?) ("Intervall"
		//
		//	intervall=Intervall | "Intervall" buchInterv=[Buchungsintervall]) ("Kategorie" kategorie+=[Kategorie] (","
		//
		//	kategorie+=[Kategorie])*)? "}";
		public ParserRule getRule() { return rule; }

		//"Buchung" name=ValidID "{" "Konto" konto=[Konto] "Betrag" betrag=INT ("Empf‰nger" empfaenger=[Kontakt] ("Empf‰ngerKonto"
		//
		//empfaengerKto=[Konto])? | "von" von=[Kontakt] ("Konto" vonKto=[Konto])?) ("Intervall" intervall=Intervall |
		//
		//"Intervall" buchInterv=[Buchungsintervall]) ("Kategorie" kategorie+=[Kategorie] ("," kategorie+=[Kategorie])*)? "}"
		public Group getGroup() { return cGroup; }

		//"Buchung"
		public Keyword getBuchungKeyword_0() { return cBuchungKeyword_0; }

		//name=ValidID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ValidID
		public RuleCall getNameValidIDParserRuleCall_1_0() { return cNameValidIDParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"Konto"
		public Keyword getKontoKeyword_3() { return cKontoKeyword_3; }

		//konto=[Konto]
		public Assignment getKontoAssignment_4() { return cKontoAssignment_4; }

		//[Konto]
		public CrossReference getKontoKontoCrossReference_4_0() { return cKontoKontoCrossReference_4_0; }

		//ID
		public RuleCall getKontoKontoIDTerminalRuleCall_4_0_1() { return cKontoKontoIDTerminalRuleCall_4_0_1; }

		//"Betrag"
		public Keyword getBetragKeyword_5() { return cBetragKeyword_5; }

		//betrag=INT
		public Assignment getBetragAssignment_6() { return cBetragAssignment_6; }

		//INT
		public RuleCall getBetragINTTerminalRuleCall_6_0() { return cBetragINTTerminalRuleCall_6_0; }

		//"Empf‰nger" empfaenger=[Kontakt] ("Empf‰ngerKonto" empfaengerKto=[Konto])? | "von" von=[Kontakt] ("Konto"
		//
		//vonKto=[Konto])?
		public Alternatives getAlternatives_7() { return cAlternatives_7; }

		//"Empf‰nger" empfaenger=[Kontakt] ("Empf‰ngerKonto" empfaengerKto=[Konto])?
		public Group getGroup_7_0() { return cGroup_7_0; }

		//"Empf‰nger"
		public Keyword getEmpf‰ngerKeyword_7_0_0() { return cEmpf‰ngerKeyword_7_0_0; }

		//empfaenger=[Kontakt]
		public Assignment getEmpfaengerAssignment_7_0_1() { return cEmpfaengerAssignment_7_0_1; }

		//[Kontakt]
		public CrossReference getEmpfaengerKontaktCrossReference_7_0_1_0() { return cEmpfaengerKontaktCrossReference_7_0_1_0; }

		//ID
		public RuleCall getEmpfaengerKontaktIDTerminalRuleCall_7_0_1_0_1() { return cEmpfaengerKontaktIDTerminalRuleCall_7_0_1_0_1; }

		//("Empf‰ngerKonto" empfaengerKto=[Konto])?
		public Group getGroup_7_0_2() { return cGroup_7_0_2; }

		//"Empf‰ngerKonto"
		public Keyword getEmpf‰ngerKontoKeyword_7_0_2_0() { return cEmpf‰ngerKontoKeyword_7_0_2_0; }

		//empfaengerKto=[Konto]
		public Assignment getEmpfaengerKtoAssignment_7_0_2_1() { return cEmpfaengerKtoAssignment_7_0_2_1; }

		//[Konto]
		public CrossReference getEmpfaengerKtoKontoCrossReference_7_0_2_1_0() { return cEmpfaengerKtoKontoCrossReference_7_0_2_1_0; }

		//ID
		public RuleCall getEmpfaengerKtoKontoIDTerminalRuleCall_7_0_2_1_0_1() { return cEmpfaengerKtoKontoIDTerminalRuleCall_7_0_2_1_0_1; }

		//"von" von=[Kontakt] ("Konto" vonKto=[Konto])?
		public Group getGroup_7_1() { return cGroup_7_1; }

		//"von"
		public Keyword getVonKeyword_7_1_0() { return cVonKeyword_7_1_0; }

		//von=[Kontakt]
		public Assignment getVonAssignment_7_1_1() { return cVonAssignment_7_1_1; }

		//[Kontakt]
		public CrossReference getVonKontaktCrossReference_7_1_1_0() { return cVonKontaktCrossReference_7_1_1_0; }

		//ID
		public RuleCall getVonKontaktIDTerminalRuleCall_7_1_1_0_1() { return cVonKontaktIDTerminalRuleCall_7_1_1_0_1; }

		//("Konto" vonKto=[Konto])?
		public Group getGroup_7_1_2() { return cGroup_7_1_2; }

		//"Konto"
		public Keyword getKontoKeyword_7_1_2_0() { return cKontoKeyword_7_1_2_0; }

		//vonKto=[Konto]
		public Assignment getVonKtoAssignment_7_1_2_1() { return cVonKtoAssignment_7_1_2_1; }

		//[Konto]
		public CrossReference getVonKtoKontoCrossReference_7_1_2_1_0() { return cVonKtoKontoCrossReference_7_1_2_1_0; }

		//ID
		public RuleCall getVonKtoKontoIDTerminalRuleCall_7_1_2_1_0_1() { return cVonKtoKontoIDTerminalRuleCall_7_1_2_1_0_1; }

		//"Intervall" intervall=Intervall | "Intervall" buchInterv=[Buchungsintervall]
		public Alternatives getAlternatives_8() { return cAlternatives_8; }

		//"Intervall" intervall=Intervall
		public Group getGroup_8_0() { return cGroup_8_0; }

		//"Intervall"
		public Keyword getIntervallKeyword_8_0_0() { return cIntervallKeyword_8_0_0; }

		//intervall=Intervall
		public Assignment getIntervallAssignment_8_0_1() { return cIntervallAssignment_8_0_1; }

		//Intervall
		public RuleCall getIntervallIntervallParserRuleCall_8_0_1_0() { return cIntervallIntervallParserRuleCall_8_0_1_0; }

		//=> "Intervall" buchInterv=[Buchungsintervall]
		public Group getGroup_8_1() { return cGroup_8_1; }

		//=> "Intervall"
		public Keyword getIntervallKeyword_8_1_0() { return cIntervallKeyword_8_1_0; }

		//buchInterv=[Buchungsintervall]
		public Assignment getBuchIntervAssignment_8_1_1() { return cBuchIntervAssignment_8_1_1; }

		//[Buchungsintervall]
		public CrossReference getBuchIntervBuchungsintervallCrossReference_8_1_1_0() { return cBuchIntervBuchungsintervallCrossReference_8_1_1_0; }

		//ID
		public RuleCall getBuchIntervBuchungsintervallIDTerminalRuleCall_8_1_1_0_1() { return cBuchIntervBuchungsintervallIDTerminalRuleCall_8_1_1_0_1; }

		//("Kategorie" kategorie+=[Kategorie] ("," kategorie+=[Kategorie])*)?
		public Group getGroup_9() { return cGroup_9; }

		//"Kategorie"
		public Keyword getKategorieKeyword_9_0() { return cKategorieKeyword_9_0; }

		//kategorie+=[Kategorie]
		public Assignment getKategorieAssignment_9_1() { return cKategorieAssignment_9_1; }

		//[Kategorie]
		public CrossReference getKategorieKategorieCrossReference_9_1_0() { return cKategorieKategorieCrossReference_9_1_0; }

		//ID
		public RuleCall getKategorieKategorieIDTerminalRuleCall_9_1_0_1() { return cKategorieKategorieIDTerminalRuleCall_9_1_0_1; }

		//("," kategorie+=[Kategorie])*
		public Group getGroup_9_2() { return cGroup_9_2; }

		//","
		public Keyword getCommaKeyword_9_2_0() { return cCommaKeyword_9_2_0; }

		//kategorie+=[Kategorie]
		public Assignment getKategorieAssignment_9_2_1() { return cKategorieAssignment_9_2_1; }

		//[Kategorie]
		public CrossReference getKategorieKategorieCrossReference_9_2_1_0() { return cKategorieKategorieCrossReference_9_2_1_0; }

		//ID
		public RuleCall getKategorieKategorieIDTerminalRuleCall_9_2_1_0_1() { return cKategorieKategorieIDTerminalRuleCall_9_2_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}

	public class KontaktElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Kontakt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cKontaktKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameValidIDParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cKontenKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cKontenAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final CrossReference cKontenKontoCrossReference_2_1_1_0 = (CrossReference)cKontenAssignment_2_1_1.eContents().get(0);
		private final RuleCall cKontenKontoIDTerminalRuleCall_2_1_1_0_1 = (RuleCall)cKontenKontoCrossReference_2_1_1_0.eContents().get(1);
		private final Group cGroup_2_1_2 = (Group)cGroup_2_1.eContents().get(2);
		private final Keyword cCommaKeyword_2_1_2_0 = (Keyword)cGroup_2_1_2.eContents().get(0);
		private final Assignment cKontenAssignment_2_1_2_1 = (Assignment)cGroup_2_1_2.eContents().get(1);
		private final CrossReference cKontenKontoCrossReference_2_1_2_1_0 = (CrossReference)cKontenAssignment_2_1_2_1.eContents().get(0);
		private final RuleCall cKontenKontoIDTerminalRuleCall_2_1_2_1_0_1 = (RuleCall)cKontenKontoCrossReference_2_1_2_1_0.eContents().get(1);
		private final Keyword cStraEKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Assignment cStrasseAssignment_2_3 = (Assignment)cGroup_2.eContents().get(3);
		private final RuleCall cStrasseSTRINGTerminalRuleCall_2_3_0 = (RuleCall)cStrasseAssignment_2_3.eContents().get(0);
		private final Keyword cPLZKeyword_2_4 = (Keyword)cGroup_2.eContents().get(4);
		private final Assignment cPlzAssignment_2_5 = (Assignment)cGroup_2.eContents().get(5);
		private final RuleCall cPlzINTTerminalRuleCall_2_5_0 = (RuleCall)cPlzAssignment_2_5.eContents().get(0);
		private final Keyword cOrtKeyword_2_6 = (Keyword)cGroup_2.eContents().get(6);
		private final Assignment cOrtAssignment_2_7 = (Assignment)cGroup_2.eContents().get(7);
		private final RuleCall cOrtSTRINGTerminalRuleCall_2_7_0 = (RuleCall)cOrtAssignment_2_7.eContents().get(0);
		private final Group cGroup_2_8 = (Group)cGroup_2.eContents().get(8);
		private final Keyword cBemerkungKeyword_2_8_0 = (Keyword)cGroup_2_8.eContents().get(0);
		private final Assignment cBemerkungAssignment_2_8_1 = (Assignment)cGroup_2_8.eContents().get(1);
		private final RuleCall cBemerkungSTRINGTerminalRuleCall_2_8_1_0 = (RuleCall)cBemerkungAssignment_2_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_9 = (Keyword)cGroup_2.eContents().get(9);
		
		//Kontakt:
		//
		//	"Kontakt" name=ValidID ("{" ("Konten" konten+=[Konto] ("," konten+=[Konto])*)? "Straﬂe" strasse=STRING "PLZ" plz=INT
		//
		//	"Ort" ort=STRING ("Bemerkung" bemerkung=STRING)? "}")?;
		public ParserRule getRule() { return rule; }

		//"Kontakt" name=ValidID ("{" ("Konten" konten+=[Konto] ("," konten+=[Konto])*)? "Straﬂe" strasse=STRING "PLZ" plz=INT
		//
		//"Ort" ort=STRING ("Bemerkung" bemerkung=STRING)? "}")?
		public Group getGroup() { return cGroup; }

		//"Kontakt"
		public Keyword getKontaktKeyword_0() { return cKontaktKeyword_0; }

		//name=ValidID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ValidID
		public RuleCall getNameValidIDParserRuleCall_1_0() { return cNameValidIDParserRuleCall_1_0; }

		//("{" ("Konten" konten+=[Konto] ("," konten+=[Konto])*)? "Straﬂe" strasse=STRING "PLZ" plz=INT "Ort" ort=STRING
		//
		//("Bemerkung" bemerkung=STRING)? "}")?
		public Group getGroup_2() { return cGroup_2; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2_0() { return cLeftCurlyBracketKeyword_2_0; }

		//("Konten" konten+=[Konto] ("," konten+=[Konto])*)?
		public Group getGroup_2_1() { return cGroup_2_1; }

		//"Konten"
		public Keyword getKontenKeyword_2_1_0() { return cKontenKeyword_2_1_0; }

		//konten+=[Konto]
		public Assignment getKontenAssignment_2_1_1() { return cKontenAssignment_2_1_1; }

		//[Konto]
		public CrossReference getKontenKontoCrossReference_2_1_1_0() { return cKontenKontoCrossReference_2_1_1_0; }

		//ID
		public RuleCall getKontenKontoIDTerminalRuleCall_2_1_1_0_1() { return cKontenKontoIDTerminalRuleCall_2_1_1_0_1; }

		//("," konten+=[Konto])*
		public Group getGroup_2_1_2() { return cGroup_2_1_2; }

		//","
		public Keyword getCommaKeyword_2_1_2_0() { return cCommaKeyword_2_1_2_0; }

		//konten+=[Konto]
		public Assignment getKontenAssignment_2_1_2_1() { return cKontenAssignment_2_1_2_1; }

		//[Konto]
		public CrossReference getKontenKontoCrossReference_2_1_2_1_0() { return cKontenKontoCrossReference_2_1_2_1_0; }

		//ID
		public RuleCall getKontenKontoIDTerminalRuleCall_2_1_2_1_0_1() { return cKontenKontoIDTerminalRuleCall_2_1_2_1_0_1; }

		//"Straﬂe"
		public Keyword getStraEKeyword_2_2() { return cStraEKeyword_2_2; }

		//strasse=STRING
		public Assignment getStrasseAssignment_2_3() { return cStrasseAssignment_2_3; }

		//STRING
		public RuleCall getStrasseSTRINGTerminalRuleCall_2_3_0() { return cStrasseSTRINGTerminalRuleCall_2_3_0; }

		//"PLZ"
		public Keyword getPLZKeyword_2_4() { return cPLZKeyword_2_4; }

		//plz=INT
		public Assignment getPlzAssignment_2_5() { return cPlzAssignment_2_5; }

		//INT
		public RuleCall getPlzINTTerminalRuleCall_2_5_0() { return cPlzINTTerminalRuleCall_2_5_0; }

		//"Ort"
		public Keyword getOrtKeyword_2_6() { return cOrtKeyword_2_6; }

		//ort=STRING
		public Assignment getOrtAssignment_2_7() { return cOrtAssignment_2_7; }

		//STRING
		public RuleCall getOrtSTRINGTerminalRuleCall_2_7_0() { return cOrtSTRINGTerminalRuleCall_2_7_0; }

		//("Bemerkung" bemerkung=STRING)?
		public Group getGroup_2_8() { return cGroup_2_8; }

		//"Bemerkung"
		public Keyword getBemerkungKeyword_2_8_0() { return cBemerkungKeyword_2_8_0; }

		//bemerkung=STRING
		public Assignment getBemerkungAssignment_2_8_1() { return cBemerkungAssignment_2_8_1; }

		//STRING
		public RuleCall getBemerkungSTRINGTerminalRuleCall_2_8_1_0() { return cBemerkungSTRINGTerminalRuleCall_2_8_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_2_9() { return cRightCurlyBracketKeyword_2_9; }
	}
	
	
	public class MONATElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "MONAT");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cALLEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cALLEMonatlichKeyword_0_0 = (Keyword)cALLEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cALLEEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cALLEAsteriskKeyword_1_0 = (Keyword)cALLEEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cJANUAREnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cJANUARJanuarKeyword_2_0 = (Keyword)cJANUAREnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cJANUAREnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cJANUARJanKeyword_3_0 = (Keyword)cJANUAREnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cFEBRUAREnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cFEBRUARFebruarKeyword_4_0 = (Keyword)cFEBRUAREnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cFEBRUAREnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cFEBRUARFebKeyword_5_0 = (Keyword)cFEBRUAREnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cMAERZEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cMAERZM‰rzKeyword_6_0 = (Keyword)cMAERZEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cMAERZEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cMAERZMarKeyword_7_0 = (Keyword)cMAERZEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cAPRILEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cAPRILAprilKeyword_8_0 = (Keyword)cAPRILEnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cAPRILEnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cAPRILAprKeyword_9_0 = (Keyword)cAPRILEnumLiteralDeclaration_9.eContents().get(0);
		private final EnumLiteralDeclaration cMAIEnumLiteralDeclaration_10 = (EnumLiteralDeclaration)cAlternatives.eContents().get(10);
		private final Keyword cMAIMaiKeyword_10_0 = (Keyword)cMAIEnumLiteralDeclaration_10.eContents().get(0);
		private final EnumLiteralDeclaration cMAIEnumLiteralDeclaration_11 = (EnumLiteralDeclaration)cAlternatives.eContents().get(11);
		private final Keyword cMAIMayKeyword_11_0 = (Keyword)cMAIEnumLiteralDeclaration_11.eContents().get(0);
		private final EnumLiteralDeclaration cJUNIEnumLiteralDeclaration_12 = (EnumLiteralDeclaration)cAlternatives.eContents().get(12);
		private final Keyword cJUNIJuniKeyword_12_0 = (Keyword)cJUNIEnumLiteralDeclaration_12.eContents().get(0);
		private final EnumLiteralDeclaration cJUNIEnumLiteralDeclaration_13 = (EnumLiteralDeclaration)cAlternatives.eContents().get(13);
		private final Keyword cJUNIJunKeyword_13_0 = (Keyword)cJUNIEnumLiteralDeclaration_13.eContents().get(0);
		private final EnumLiteralDeclaration cJULIEnumLiteralDeclaration_14 = (EnumLiteralDeclaration)cAlternatives.eContents().get(14);
		private final Keyword cJULIJuliKeyword_14_0 = (Keyword)cJULIEnumLiteralDeclaration_14.eContents().get(0);
		private final EnumLiteralDeclaration cJULIEnumLiteralDeclaration_15 = (EnumLiteralDeclaration)cAlternatives.eContents().get(15);
		private final Keyword cJULIJulKeyword_15_0 = (Keyword)cJULIEnumLiteralDeclaration_15.eContents().get(0);
		private final EnumLiteralDeclaration cAUGUSTEnumLiteralDeclaration_16 = (EnumLiteralDeclaration)cAlternatives.eContents().get(16);
		private final Keyword cAUGUSTAugustKeyword_16_0 = (Keyword)cAUGUSTEnumLiteralDeclaration_16.eContents().get(0);
		private final EnumLiteralDeclaration cAUGUSTEnumLiteralDeclaration_17 = (EnumLiteralDeclaration)cAlternatives.eContents().get(17);
		private final Keyword cAUGUSTAugKeyword_17_0 = (Keyword)cAUGUSTEnumLiteralDeclaration_17.eContents().get(0);
		private final EnumLiteralDeclaration cSEPTEMBEREnumLiteralDeclaration_18 = (EnumLiteralDeclaration)cAlternatives.eContents().get(18);
		private final Keyword cSEPTEMBERSeptemberKeyword_18_0 = (Keyword)cSEPTEMBEREnumLiteralDeclaration_18.eContents().get(0);
		private final EnumLiteralDeclaration cSEPTEMBEREnumLiteralDeclaration_19 = (EnumLiteralDeclaration)cAlternatives.eContents().get(19);
		private final Keyword cSEPTEMBERSepKeyword_19_0 = (Keyword)cSEPTEMBEREnumLiteralDeclaration_19.eContents().get(0);
		private final EnumLiteralDeclaration cOKTOBEREnumLiteralDeclaration_20 = (EnumLiteralDeclaration)cAlternatives.eContents().get(20);
		private final Keyword cOKTOBEROktoberKeyword_20_0 = (Keyword)cOKTOBEREnumLiteralDeclaration_20.eContents().get(0);
		private final EnumLiteralDeclaration cOKTOBEREnumLiteralDeclaration_21 = (EnumLiteralDeclaration)cAlternatives.eContents().get(21);
		private final Keyword cOKTOBEROktKeyword_21_0 = (Keyword)cOKTOBEREnumLiteralDeclaration_21.eContents().get(0);
		private final EnumLiteralDeclaration cNOVEMBEREnumLiteralDeclaration_22 = (EnumLiteralDeclaration)cAlternatives.eContents().get(22);
		private final Keyword cNOVEMBERNovemberKeyword_22_0 = (Keyword)cNOVEMBEREnumLiteralDeclaration_22.eContents().get(0);
		private final EnumLiteralDeclaration cNOVEMBEREnumLiteralDeclaration_23 = (EnumLiteralDeclaration)cAlternatives.eContents().get(23);
		private final Keyword cNOVEMBERNovKeyword_23_0 = (Keyword)cNOVEMBEREnumLiteralDeclaration_23.eContents().get(0);
		private final EnumLiteralDeclaration cDEZEMBEREnumLiteralDeclaration_24 = (EnumLiteralDeclaration)cAlternatives.eContents().get(24);
		private final Keyword cDEZEMBERDezemberKeyword_24_0 = (Keyword)cDEZEMBEREnumLiteralDeclaration_24.eContents().get(0);
		private final EnumLiteralDeclaration cDEZEMBEREnumLiteralDeclaration_25 = (EnumLiteralDeclaration)cAlternatives.eContents().get(25);
		private final Keyword cDEZEMBERDezKeyword_25_0 = (Keyword)cDEZEMBEREnumLiteralDeclaration_25.eContents().get(0);
		
		//enum MONAT:
		//
		//	ALLE="monatlich" | ALLE="*" | JANUAR="Januar" | JANUAR="Jan" | FEBRUAR="Februar" | FEBRUAR="Feb" | MAERZ="M‰rz" |
		//
		//	MAERZ="Mar" | APRIL="April" | APRIL="Apr" | MAI="Mai" | MAI="May" | JUNI="Juni" | JUNI="Jun" | JULI="Juli" |
		//
		//	JULI="Jul" | AUGUST="August" | AUGUST="Aug" | SEPTEMBER="September" | SEPTEMBER="Sep" | OKTOBER="Oktober" |
		//
		//	OKTOBER="Okt" | NOVEMBER="November" | NOVEMBER="Nov" | DEZEMBER="Dezember" | DEZEMBER="Dez";
		public EnumRule getRule() { return rule; }

		//ALLE="monatlich" | ALLE="*" | JANUAR="Januar" | JANUAR="Jan" | FEBRUAR="Februar" | FEBRUAR="Feb" | MAERZ="M‰rz" |
		//
		//MAERZ="Mar" | APRIL="April" | APRIL="Apr" | MAI="Mai" | MAI="May" | JUNI="Juni" | JUNI="Jun" | JULI="Juli" |
		//
		//JULI="Jul" | AUGUST="August" | AUGUST="Aug" | SEPTEMBER="September" | SEPTEMBER="Sep" | OKTOBER="Oktober" |
		//
		//OKTOBER="Okt" | NOVEMBER="November" | NOVEMBER="Nov" | DEZEMBER="Dezember" | DEZEMBER="Dez"
		public Alternatives getAlternatives() { return cAlternatives; }

		//ALLE="monatlich"
		public EnumLiteralDeclaration getALLEEnumLiteralDeclaration_0() { return cALLEEnumLiteralDeclaration_0; }

		//"monatlich"
		public Keyword getALLEMonatlichKeyword_0_0() { return cALLEMonatlichKeyword_0_0; }

		//ALLE="*"
		public EnumLiteralDeclaration getALLEEnumLiteralDeclaration_1() { return cALLEEnumLiteralDeclaration_1; }

		//"*"
		public Keyword getALLEAsteriskKeyword_1_0() { return cALLEAsteriskKeyword_1_0; }

		//JANUAR="Januar"
		public EnumLiteralDeclaration getJANUAREnumLiteralDeclaration_2() { return cJANUAREnumLiteralDeclaration_2; }

		//"Januar"
		public Keyword getJANUARJanuarKeyword_2_0() { return cJANUARJanuarKeyword_2_0; }

		//JANUAR="Jan"
		public EnumLiteralDeclaration getJANUAREnumLiteralDeclaration_3() { return cJANUAREnumLiteralDeclaration_3; }

		//"Jan"
		public Keyword getJANUARJanKeyword_3_0() { return cJANUARJanKeyword_3_0; }

		//FEBRUAR="Februar"
		public EnumLiteralDeclaration getFEBRUAREnumLiteralDeclaration_4() { return cFEBRUAREnumLiteralDeclaration_4; }

		//"Februar"
		public Keyword getFEBRUARFebruarKeyword_4_0() { return cFEBRUARFebruarKeyword_4_0; }

		//FEBRUAR="Feb"
		public EnumLiteralDeclaration getFEBRUAREnumLiteralDeclaration_5() { return cFEBRUAREnumLiteralDeclaration_5; }

		//"Feb"
		public Keyword getFEBRUARFebKeyword_5_0() { return cFEBRUARFebKeyword_5_0; }

		//MAERZ="M‰rz"
		public EnumLiteralDeclaration getMAERZEnumLiteralDeclaration_6() { return cMAERZEnumLiteralDeclaration_6; }

		//"M‰rz"
		public Keyword getMAERZM‰rzKeyword_6_0() { return cMAERZM‰rzKeyword_6_0; }

		//MAERZ="Mar"
		public EnumLiteralDeclaration getMAERZEnumLiteralDeclaration_7() { return cMAERZEnumLiteralDeclaration_7; }

		//"Mar"
		public Keyword getMAERZMarKeyword_7_0() { return cMAERZMarKeyword_7_0; }

		//APRIL="April"
		public EnumLiteralDeclaration getAPRILEnumLiteralDeclaration_8() { return cAPRILEnumLiteralDeclaration_8; }

		//"April"
		public Keyword getAPRILAprilKeyword_8_0() { return cAPRILAprilKeyword_8_0; }

		//APRIL="Apr"
		public EnumLiteralDeclaration getAPRILEnumLiteralDeclaration_9() { return cAPRILEnumLiteralDeclaration_9; }

		//"Apr"
		public Keyword getAPRILAprKeyword_9_0() { return cAPRILAprKeyword_9_0; }

		//MAI="Mai"
		public EnumLiteralDeclaration getMAIEnumLiteralDeclaration_10() { return cMAIEnumLiteralDeclaration_10; }

		//"Mai"
		public Keyword getMAIMaiKeyword_10_0() { return cMAIMaiKeyword_10_0; }

		//MAI="May"
		public EnumLiteralDeclaration getMAIEnumLiteralDeclaration_11() { return cMAIEnumLiteralDeclaration_11; }

		//"May"
		public Keyword getMAIMayKeyword_11_0() { return cMAIMayKeyword_11_0; }

		//JUNI="Juni"
		public EnumLiteralDeclaration getJUNIEnumLiteralDeclaration_12() { return cJUNIEnumLiteralDeclaration_12; }

		//"Juni"
		public Keyword getJUNIJuniKeyword_12_0() { return cJUNIJuniKeyword_12_0; }

		//JUNI="Jun"
		public EnumLiteralDeclaration getJUNIEnumLiteralDeclaration_13() { return cJUNIEnumLiteralDeclaration_13; }

		//"Jun"
		public Keyword getJUNIJunKeyword_13_0() { return cJUNIJunKeyword_13_0; }

		//JULI="Juli"
		public EnumLiteralDeclaration getJULIEnumLiteralDeclaration_14() { return cJULIEnumLiteralDeclaration_14; }

		//"Juli"
		public Keyword getJULIJuliKeyword_14_0() { return cJULIJuliKeyword_14_0; }

		//JULI="Jul"
		public EnumLiteralDeclaration getJULIEnumLiteralDeclaration_15() { return cJULIEnumLiteralDeclaration_15; }

		//"Jul"
		public Keyword getJULIJulKeyword_15_0() { return cJULIJulKeyword_15_0; }

		//AUGUST="August"
		public EnumLiteralDeclaration getAUGUSTEnumLiteralDeclaration_16() { return cAUGUSTEnumLiteralDeclaration_16; }

		//"August"
		public Keyword getAUGUSTAugustKeyword_16_0() { return cAUGUSTAugustKeyword_16_0; }

		//AUGUST="Aug"
		public EnumLiteralDeclaration getAUGUSTEnumLiteralDeclaration_17() { return cAUGUSTEnumLiteralDeclaration_17; }

		//"Aug"
		public Keyword getAUGUSTAugKeyword_17_0() { return cAUGUSTAugKeyword_17_0; }

		//SEPTEMBER="September"
		public EnumLiteralDeclaration getSEPTEMBEREnumLiteralDeclaration_18() { return cSEPTEMBEREnumLiteralDeclaration_18; }

		//"September"
		public Keyword getSEPTEMBERSeptemberKeyword_18_0() { return cSEPTEMBERSeptemberKeyword_18_0; }

		//SEPTEMBER="Sep"
		public EnumLiteralDeclaration getSEPTEMBEREnumLiteralDeclaration_19() { return cSEPTEMBEREnumLiteralDeclaration_19; }

		//"Sep"
		public Keyword getSEPTEMBERSepKeyword_19_0() { return cSEPTEMBERSepKeyword_19_0; }

		//OKTOBER="Oktober"
		public EnumLiteralDeclaration getOKTOBEREnumLiteralDeclaration_20() { return cOKTOBEREnumLiteralDeclaration_20; }

		//"Oktober"
		public Keyword getOKTOBEROktoberKeyword_20_0() { return cOKTOBEROktoberKeyword_20_0; }

		//OKTOBER="Okt"
		public EnumLiteralDeclaration getOKTOBEREnumLiteralDeclaration_21() { return cOKTOBEREnumLiteralDeclaration_21; }

		//"Okt"
		public Keyword getOKTOBEROktKeyword_21_0() { return cOKTOBEROktKeyword_21_0; }

		//NOVEMBER="November"
		public EnumLiteralDeclaration getNOVEMBEREnumLiteralDeclaration_22() { return cNOVEMBEREnumLiteralDeclaration_22; }

		//"November"
		public Keyword getNOVEMBERNovemberKeyword_22_0() { return cNOVEMBERNovemberKeyword_22_0; }

		//NOVEMBER="Nov"
		public EnumLiteralDeclaration getNOVEMBEREnumLiteralDeclaration_23() { return cNOVEMBEREnumLiteralDeclaration_23; }

		//"Nov"
		public Keyword getNOVEMBERNovKeyword_23_0() { return cNOVEMBERNovKeyword_23_0; }

		//DEZEMBER="Dezember"
		public EnumLiteralDeclaration getDEZEMBEREnumLiteralDeclaration_24() { return cDEZEMBEREnumLiteralDeclaration_24; }

		//"Dezember"
		public Keyword getDEZEMBERDezemberKeyword_24_0() { return cDEZEMBERDezemberKeyword_24_0; }

		//DEZEMBER="Dez"
		public EnumLiteralDeclaration getDEZEMBEREnumLiteralDeclaration_25() { return cDEZEMBEREnumLiteralDeclaration_25; }

		//"Dez"
		public Keyword getDEZEMBERDezKeyword_25_0() { return cDEZEMBERDezKeyword_25_0; }
	}
	
	private FinModelFileElements pFinModelFile;
	private ElementElements pElement;
	private ImportElements pImport;
	private KontoElements pKonto;
	private TerminalRule tTAG;
	private MONATElements unknownRuleMONAT;
	private BuchungsintervallElements pBuchungsintervall;
	private IntervallElements pIntervall;
	private KategorieElements pKategorie;
	private BuchungElements pBuchung;
	private KontaktElements pKontakt;
	
	private final Grammar grammar;

	private XbaseGrammarAccess gaXbase;

	@Inject
	public FinGrammarAccess(GrammarProvider grammarProvider,
		XbaseGrammarAccess gaXbase) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaXbase = gaXbase;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.nie.fin.Fin".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public XbaseGrammarAccess getXbaseGrammarAccess() {
		return gaXbase;
	}

	
	//FinModelFile:
	//
	//	("package" name=QualifiedName)? imports+=Import* elements+=Element*;
	public FinModelFileElements getFinModelFileAccess() {
		return (pFinModelFile != null) ? pFinModelFile : (pFinModelFile = new FinModelFileElements());
	}
	
	public ParserRule getFinModelFileRule() {
		return getFinModelFileAccess().getRule();
	}

	//Element:
	//
	//	Konto | Buchung | Kontakt | Buchungsintervall | Kategorie;
	public ElementElements getElementAccess() {
		return (pElement != null) ? pElement : (pElement = new ElementElements());
	}
	
	public ParserRule getElementRule() {
		return getElementAccess().getRule();
	}

	//Import:
	//
	//	"import" importedNamespace=QualifiedName;
	public ImportElements getImportAccess() {
		return (pImport != null) ? pImport : (pImport = new ImportElements());
	}
	
	public ParserRule getImportRule() {
		return getImportAccess().getRule();
	}

	//Konto:
	//
	//	"Konto" name=ValidID "{" "KtoNr" ktoNr=INT "Blz" blz=INT "Bank" bank=[Kontakt] "Verwendung" verwendung=STRING
	//
	//	"Inhaber" inhaber=[Kontakt] "}";
	public KontoElements getKontoAccess() {
		return (pKonto != null) ? pKonto : (pKonto = new KontoElements());
	}
	
	public ParserRule getKontoRule() {
		return getKontoAccess().getRule();
	}

	//terminal TAG:
	//
	//	"1." | "2." | "3." | "4." | "5." | "6." | "7." | "8." | "9." | "10." | "11." | "12." | "13." | "14." | "15." | "16."
	//
	//	| "17." | "18." | "19." | "20." | "21." | "22." | "23." | "24." | "25." | "26." | "27." | "28." | "29." | "30." |
	//
	//	"31.";
	public TerminalRule getTAGRule() {
		return (tTAG != null) ? tTAG : (tTAG = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "TAG"));
	} 

	//enum MONAT:
	//
	//	ALLE="monatlich" | ALLE="*" | JANUAR="Januar" | JANUAR="Jan" | FEBRUAR="Februar" | FEBRUAR="Feb" | MAERZ="M‰rz" |
	//
	//	MAERZ="Mar" | APRIL="April" | APRIL="Apr" | MAI="Mai" | MAI="May" | JUNI="Juni" | JUNI="Jun" | JULI="Juli" |
	//
	//	JULI="Jul" | AUGUST="August" | AUGUST="Aug" | SEPTEMBER="September" | SEPTEMBER="Sep" | OKTOBER="Oktober" |
	//
	//	OKTOBER="Okt" | NOVEMBER="November" | NOVEMBER="Nov" | DEZEMBER="Dezember" | DEZEMBER="Dez";
	public MONATElements getMONATAccess() {
		return (unknownRuleMONAT != null) ? unknownRuleMONAT : (unknownRuleMONAT = new MONATElements());
	}
	
	public EnumRule getMONATRule() {
		return getMONATAccess().getRule();
	}

	//Buchungsintervall:
	//
	//	"Buchungsintervall" name=ValidID "{" intervall=Intervall "}";
	public BuchungsintervallElements getBuchungsintervallAccess() {
		return (pBuchungsintervall != null) ? pBuchungsintervall : (pBuchungsintervall = new BuchungsintervallElements());
	}
	
	public ParserRule getBuchungsintervallRule() {
		return getBuchungsintervallAccess().getRule();
	}

	//Intervall:
	//
	//	"Zum" tag=TAG "der Monate" (monate+=MONAT ("," monate+=MONAT)*);
	public IntervallElements getIntervallAccess() {
		return (pIntervall != null) ? pIntervall : (pIntervall = new IntervallElements());
	}
	
	public ParserRule getIntervallRule() {
		return getIntervallAccess().getRule();
	}

	//Kategorie:
	//
	//	"Kategorie" name=ValidID;
	public KategorieElements getKategorieAccess() {
		return (pKategorie != null) ? pKategorie : (pKategorie = new KategorieElements());
	}
	
	public ParserRule getKategorieRule() {
		return getKategorieAccess().getRule();
	}

	//Buchung:
	//
	//	"Buchung" name=ValidID "{" "Konto" konto=[Konto] "Betrag" betrag=INT ("Empf‰nger" empfaenger=[Kontakt]
	//
	//	("Empf‰ngerKonto" empfaengerKto=[Konto])? | "von" von=[Kontakt] ("Konto" vonKto=[Konto])?) ("Intervall"
	//
	//	intervall=Intervall | "Intervall" buchInterv=[Buchungsintervall]) ("Kategorie" kategorie+=[Kategorie] (","
	//
	//	kategorie+=[Kategorie])*)? "}";
	public BuchungElements getBuchungAccess() {
		return (pBuchung != null) ? pBuchung : (pBuchung = new BuchungElements());
	}
	
	public ParserRule getBuchungRule() {
		return getBuchungAccess().getRule();
	}

	//Kontakt:
	//
	//	"Kontakt" name=ValidID ("{" ("Konten" konten+=[Konto] ("," konten+=[Konto])*)? "Straﬂe" strasse=STRING "PLZ" plz=INT
	//
	//	"Ort" ort=STRING ("Bemerkung" bemerkung=STRING)? "}")?;
	public KontaktElements getKontaktAccess() {
		return (pKontakt != null) ? pKontakt : (pKontakt = new KontaktElements());
	}
	
	public ParserRule getKontaktRule() {
		return getKontaktAccess().getRule();
	}

	//XExpression:
	//
	//	XAssignment;
	public XbaseGrammarAccess.XExpressionElements getXExpressionAccess() {
		return gaXbase.getXExpressionAccess();
	}
	
	public ParserRule getXExpressionRule() {
		return getXExpressionAccess().getRule();
	}

	//XAssignment returns XExpression:
	//
	//	{XAssignment} / * (declaringType=[types::JvmDeclaredType] '::')? * / feature=[types::JvmIdentifiableElement|ValidID]
	//
	//	OpSingleAssign value=XAssignment | XOrExpression (=> ({XBinaryOperation.leftOperand=current}
	//
	//	feature=[types::JvmIdentifiableElement|OpMultiAssign]) rightOperand=XAssignment)?;
	public XbaseGrammarAccess.XAssignmentElements getXAssignmentAccess() {
		return gaXbase.getXAssignmentAccess();
	}
	
	public ParserRule getXAssignmentRule() {
		return getXAssignmentAccess().getRule();
	}

	//OpSingleAssign:
	//
	//	"=";
	public XbaseGrammarAccess.OpSingleAssignElements getOpSingleAssignAccess() {
		return gaXbase.getOpSingleAssignAccess();
	}
	
	public ParserRule getOpSingleAssignRule() {
		return getOpSingleAssignAccess().getRule();
	}

	//OpMultiAssign:
	//
	//	"+=";
	public XbaseGrammarAccess.OpMultiAssignElements getOpMultiAssignAccess() {
		return gaXbase.getOpMultiAssignAccess();
	}
	
	public ParserRule getOpMultiAssignRule() {
		return getOpMultiAssignAccess().getRule();
	}

	//XOrExpression returns XExpression:
	//
	//	XAndExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpOr])
	//
	//	rightOperand=XAndExpression)*;
	public XbaseGrammarAccess.XOrExpressionElements getXOrExpressionAccess() {
		return gaXbase.getXOrExpressionAccess();
	}
	
	public ParserRule getXOrExpressionRule() {
		return getXOrExpressionAccess().getRule();
	}

	//OpOr:
	//
	//	"||";
	public XbaseGrammarAccess.OpOrElements getOpOrAccess() {
		return gaXbase.getOpOrAccess();
	}
	
	public ParserRule getOpOrRule() {
		return getOpOrAccess().getRule();
	}

	//XAndExpression returns XExpression:
	//
	//	XEqualityExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpAnd])
	//
	//	rightOperand=XEqualityExpression)*;
	public XbaseGrammarAccess.XAndExpressionElements getXAndExpressionAccess() {
		return gaXbase.getXAndExpressionAccess();
	}
	
	public ParserRule getXAndExpressionRule() {
		return getXAndExpressionAccess().getRule();
	}

	//OpAnd:
	//
	//	"&&";
	public XbaseGrammarAccess.OpAndElements getOpAndAccess() {
		return gaXbase.getOpAndAccess();
	}
	
	public ParserRule getOpAndRule() {
		return getOpAndAccess().getRule();
	}

	//XEqualityExpression returns XExpression:
	//
	//	XRelationalExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpEquality])
	//
	//	rightOperand=XRelationalExpression)*;
	public XbaseGrammarAccess.XEqualityExpressionElements getXEqualityExpressionAccess() {
		return gaXbase.getXEqualityExpressionAccess();
	}
	
	public ParserRule getXEqualityExpressionRule() {
		return getXEqualityExpressionAccess().getRule();
	}

	//OpEquality:
	//
	//	"==" | "!=";
	public XbaseGrammarAccess.OpEqualityElements getOpEqualityAccess() {
		return gaXbase.getOpEqualityAccess();
	}
	
	public ParserRule getOpEqualityRule() {
		return getOpEqualityAccess().getRule();
	}

	//XRelationalExpression returns XExpression:
	//
	//	XOtherOperatorExpression (=> ({XInstanceOfExpression.expression=current} "instanceof") type=JvmTypeReference | =>
	//
	//	({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpCompare])
	//
	//	rightOperand=XOtherOperatorExpression)*;
	public XbaseGrammarAccess.XRelationalExpressionElements getXRelationalExpressionAccess() {
		return gaXbase.getXRelationalExpressionAccess();
	}
	
	public ParserRule getXRelationalExpressionRule() {
		return getXRelationalExpressionAccess().getRule();
	}

	//OpCompare:
	//
	//	">=" | "<=" | ">" | "<";
	public XbaseGrammarAccess.OpCompareElements getOpCompareAccess() {
		return gaXbase.getOpCompareAccess();
	}
	
	public ParserRule getOpCompareRule() {
		return getOpCompareAccess().getRule();
	}

	//XOtherOperatorExpression returns XExpression:
	//
	//	XAdditiveExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpOther])
	//
	//	rightOperand=XAdditiveExpression)*;
	public XbaseGrammarAccess.XOtherOperatorExpressionElements getXOtherOperatorExpressionAccess() {
		return gaXbase.getXOtherOperatorExpressionAccess();
	}
	
	public ParserRule getXOtherOperatorExpressionRule() {
		return getXOtherOperatorExpressionAccess().getRule();
	}

	//OpOther:
	//
	//	"->" | ".." | "=>" | ">" (=> (">" ">") | ">") | "<" (=> ("<" "<") | "<") | "<>" | "?:" | "<=>";
	public XbaseGrammarAccess.OpOtherElements getOpOtherAccess() {
		return gaXbase.getOpOtherAccess();
	}
	
	public ParserRule getOpOtherRule() {
		return getOpOtherAccess().getRule();
	}

	//XAdditiveExpression returns XExpression:
	//
	//	XMultiplicativeExpression (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpAdd])
	//
	//	rightOperand=XMultiplicativeExpression)*;
	public XbaseGrammarAccess.XAdditiveExpressionElements getXAdditiveExpressionAccess() {
		return gaXbase.getXAdditiveExpressionAccess();
	}
	
	public ParserRule getXAdditiveExpressionRule() {
		return getXAdditiveExpressionAccess().getRule();
	}

	//OpAdd:
	//
	//	"+" | "-";
	public XbaseGrammarAccess.OpAddElements getOpAddAccess() {
		return gaXbase.getOpAddAccess();
	}
	
	public ParserRule getOpAddRule() {
		return getOpAddAccess().getRule();
	}

	//XMultiplicativeExpression returns XExpression:
	//
	//	XUnaryOperation (=> ({XBinaryOperation.leftOperand=current} feature=[types::JvmIdentifiableElement|OpMulti])
	//
	//	rightOperand=XUnaryOperation)*;
	public XbaseGrammarAccess.XMultiplicativeExpressionElements getXMultiplicativeExpressionAccess() {
		return gaXbase.getXMultiplicativeExpressionAccess();
	}
	
	public ParserRule getXMultiplicativeExpressionRule() {
		return getXMultiplicativeExpressionAccess().getRule();
	}

	//OpMulti:
	//
	//	"*" | "**" | "/" | "%";
	public XbaseGrammarAccess.OpMultiElements getOpMultiAccess() {
		return gaXbase.getOpMultiAccess();
	}
	
	public ParserRule getOpMultiRule() {
		return getOpMultiAccess().getRule();
	}

	//XUnaryOperation returns XExpression:
	//
	//	{XUnaryOperation} feature=[types::JvmIdentifiableElement|OpUnary] operand=XCastedExpression | XCastedExpression;
	public XbaseGrammarAccess.XUnaryOperationElements getXUnaryOperationAccess() {
		return gaXbase.getXUnaryOperationAccess();
	}
	
	public ParserRule getXUnaryOperationRule() {
		return getXUnaryOperationAccess().getRule();
	}

	//OpUnary:
	//
	//	"!" | "-" | "+";
	public XbaseGrammarAccess.OpUnaryElements getOpUnaryAccess() {
		return gaXbase.getOpUnaryAccess();
	}
	
	public ParserRule getOpUnaryRule() {
		return getOpUnaryAccess().getRule();
	}

	//XCastedExpression returns XExpression:
	//
	//	XMemberFeatureCall (=> ({XCastedExpression.target=current} "as") type=JvmTypeReference)*;
	public XbaseGrammarAccess.XCastedExpressionElements getXCastedExpressionAccess() {
		return gaXbase.getXCastedExpressionAccess();
	}
	
	public ParserRule getXCastedExpressionRule() {
		return getXCastedExpressionAccess().getRule();
	}

	//XMemberFeatureCall returns XExpression:
	//
	//	XPrimaryExpression (=> ({XAssignment.assignable=current} "." feature=[types::JvmIdentifiableElement|ValidID]
	//
	//	OpSingleAssign) value=XAssignment | => ({XMemberFeatureCall.memberCallTarget=current} ("." | nullSafe?="?." |
	//
	//	spreading?="*.")) ("<" typeArguments+=JvmArgumentTypeReference ("," typeArguments+=JvmArgumentTypeReference)* ">")?
	//
	//	feature=[types::JvmIdentifiableElement|ValidID] (=> explicitOperationCall?="(" (memberCallArguments+=XShortClosure |
	//
	//	memberCallArguments+=XExpression ("," memberCallArguments+=XExpression)*)? ")")? memberCallArguments+=XClosure?)*;
	public XbaseGrammarAccess.XMemberFeatureCallElements getXMemberFeatureCallAccess() {
		return gaXbase.getXMemberFeatureCallAccess();
	}
	
	public ParserRule getXMemberFeatureCallRule() {
		return getXMemberFeatureCallAccess().getRule();
	}

	//XPrimaryExpression returns XExpression:
	//
	//	XConstructorCall | XBlockExpression | XSwitchExpression | XFeatureCall | XLiteral | XIfExpression |
	//
	//	XForLoopExpression | XWhileExpression | XDoWhileExpression | XThrowExpression | XReturnExpression |
	//
	//	XTryCatchFinallyExpression | XParenthesizedExpression;
	public XbaseGrammarAccess.XPrimaryExpressionElements getXPrimaryExpressionAccess() {
		return gaXbase.getXPrimaryExpressionAccess();
	}
	
	public ParserRule getXPrimaryExpressionRule() {
		return getXPrimaryExpressionAccess().getRule();
	}

	//XLiteral returns XExpression:
	//
	//	XClosure | XBooleanLiteral | XNumberLiteral | XNullLiteral | XStringLiteral | XTypeLiteral;
	public XbaseGrammarAccess.XLiteralElements getXLiteralAccess() {
		return gaXbase.getXLiteralAccess();
	}
	
	public ParserRule getXLiteralRule() {
		return getXLiteralAccess().getRule();
	}

	//XClosure returns XExpression:
	//
	//	=> ({XClosure} "[") => ((declaredFormalParameters+=JvmFormalParameter (","
	//
	//	declaredFormalParameters+=JvmFormalParameter)*)? explicitSyntax?="|")? expression=XExpressionInClosure "]";
	public XbaseGrammarAccess.XClosureElements getXClosureAccess() {
		return gaXbase.getXClosureAccess();
	}
	
	public ParserRule getXClosureRule() {
		return getXClosureAccess().getRule();
	}

	//XExpressionInClosure returns XExpression:
	//
	//	{XBlockExpression} (expressions+=XExpressionInsideBlock ";"?)*;
	public XbaseGrammarAccess.XExpressionInClosureElements getXExpressionInClosureAccess() {
		return gaXbase.getXExpressionInClosureAccess();
	}
	
	public ParserRule getXExpressionInClosureRule() {
		return getXExpressionInClosureAccess().getRule();
	}

	//XShortClosure returns XExpression:
	//
	//	=> ({XClosure} (declaredFormalParameters+=JvmFormalParameter ("," declaredFormalParameters+=JvmFormalParameter)*)?
	//
	//	explicitSyntax?="|") expression=XExpression;
	public XbaseGrammarAccess.XShortClosureElements getXShortClosureAccess() {
		return gaXbase.getXShortClosureAccess();
	}
	
	public ParserRule getXShortClosureRule() {
		return getXShortClosureAccess().getRule();
	}

	//XParenthesizedExpression returns XExpression:
	//
	//	"(" XExpression ")";
	public XbaseGrammarAccess.XParenthesizedExpressionElements getXParenthesizedExpressionAccess() {
		return gaXbase.getXParenthesizedExpressionAccess();
	}
	
	public ParserRule getXParenthesizedExpressionRule() {
		return getXParenthesizedExpressionAccess().getRule();
	}

	//XIfExpression returns XExpression:
	//
	//	{XIfExpression} "if" "(" if=XExpression ")" then=XExpression ("else" else=XExpression)?;
	public XbaseGrammarAccess.XIfExpressionElements getXIfExpressionAccess() {
		return gaXbase.getXIfExpressionAccess();
	}
	
	public ParserRule getXIfExpressionRule() {
		return getXIfExpressionAccess().getRule();
	}

	//XSwitchExpression returns XExpression:
	//
	//	{XSwitchExpression} "switch" (=> (localVarName=ValidID ":")? switch=XExpression | => ("(" localVarName=ValidID ":")
	//
	//	switch=XExpression ")") "{" cases+=XCasePart+ ("default" ":" default=XExpression)? "}";
	public XbaseGrammarAccess.XSwitchExpressionElements getXSwitchExpressionAccess() {
		return gaXbase.getXSwitchExpressionAccess();
	}
	
	public ParserRule getXSwitchExpressionRule() {
		return getXSwitchExpressionAccess().getRule();
	}

	//XCasePart:
	//
	//	typeGuard=JvmTypeReference? ("case" case=XExpression)? ":" then=XExpression;
	public XbaseGrammarAccess.XCasePartElements getXCasePartAccess() {
		return gaXbase.getXCasePartAccess();
	}
	
	public ParserRule getXCasePartRule() {
		return getXCasePartAccess().getRule();
	}

	//XForLoopExpression returns XExpression:
	//
	//	{XForLoopExpression} "for" "(" declaredParam=JvmFormalParameter ":" forExpression=XExpression ")"
	//
	//	eachExpression=XExpression;
	public XbaseGrammarAccess.XForLoopExpressionElements getXForLoopExpressionAccess() {
		return gaXbase.getXForLoopExpressionAccess();
	}
	
	public ParserRule getXForLoopExpressionRule() {
		return getXForLoopExpressionAccess().getRule();
	}

	//XWhileExpression returns XExpression:
	//
	//	{XWhileExpression} "while" "(" predicate=XExpression ")" body=XExpression;
	public XbaseGrammarAccess.XWhileExpressionElements getXWhileExpressionAccess() {
		return gaXbase.getXWhileExpressionAccess();
	}
	
	public ParserRule getXWhileExpressionRule() {
		return getXWhileExpressionAccess().getRule();
	}

	//XDoWhileExpression returns XExpression:
	//
	//	{XDoWhileExpression} "do" body=XExpression "while" "(" predicate=XExpression ")";
	public XbaseGrammarAccess.XDoWhileExpressionElements getXDoWhileExpressionAccess() {
		return gaXbase.getXDoWhileExpressionAccess();
	}
	
	public ParserRule getXDoWhileExpressionRule() {
		return getXDoWhileExpressionAccess().getRule();
	}

	//XBlockExpression returns XExpression:
	//
	//	{XBlockExpression} "{" (expressions+=XExpressionInsideBlock ";"?)* "}";
	public XbaseGrammarAccess.XBlockExpressionElements getXBlockExpressionAccess() {
		return gaXbase.getXBlockExpressionAccess();
	}
	
	public ParserRule getXBlockExpressionRule() {
		return getXBlockExpressionAccess().getRule();
	}

	//XExpressionInsideBlock returns XExpression:
	//
	//	XVariableDeclaration | XExpression;
	public XbaseGrammarAccess.XExpressionInsideBlockElements getXExpressionInsideBlockAccess() {
		return gaXbase.getXExpressionInsideBlockAccess();
	}
	
	public ParserRule getXExpressionInsideBlockRule() {
		return getXExpressionInsideBlockAccess().getRule();
	}

	//XVariableDeclaration returns XExpression:
	//
	//	{XVariableDeclaration} (writeable?="var" | "val") (=> (type=JvmTypeReference name=ValidID) | name=ValidID) ("="
	//
	//	right=XExpression)?;
	public XbaseGrammarAccess.XVariableDeclarationElements getXVariableDeclarationAccess() {
		return gaXbase.getXVariableDeclarationAccess();
	}
	
	public ParserRule getXVariableDeclarationRule() {
		return getXVariableDeclarationAccess().getRule();
	}

	//JvmFormalParameter returns types::JvmFormalParameter:
	//
	//	parameterType=JvmTypeReference? name=ValidID;
	public XbaseGrammarAccess.JvmFormalParameterElements getJvmFormalParameterAccess() {
		return gaXbase.getJvmFormalParameterAccess();
	}
	
	public ParserRule getJvmFormalParameterRule() {
		return getJvmFormalParameterAccess().getRule();
	}

	//FullJvmFormalParameter returns types::JvmFormalParameter:
	//
	//	parameterType=JvmTypeReference name=ValidID;
	public XbaseGrammarAccess.FullJvmFormalParameterElements getFullJvmFormalParameterAccess() {
		return gaXbase.getFullJvmFormalParameterAccess();
	}
	
	public ParserRule getFullJvmFormalParameterRule() {
		return getFullJvmFormalParameterAccess().getRule();
	}

	//XFeatureCall returns XExpression:
	//
	//	{XFeatureCall} declaringType=[types::JvmDeclaredType|StaticQualifier]? ("<" typeArguments+=JvmArgumentTypeReference
	//
	//	("," typeArguments+=JvmArgumentTypeReference)* ">")? feature=[types::JvmIdentifiableElement|IdOrSuper] (=>
	//
	//	explicitOperationCall?="(" (featureCallArguments+=XShortClosure | featureCallArguments+=XExpression (","
	//
	//	featureCallArguments+=XExpression)*)? ")")? featureCallArguments+=XClosure?;
	public XbaseGrammarAccess.XFeatureCallElements getXFeatureCallAccess() {
		return gaXbase.getXFeatureCallAccess();
	}
	
	public ParserRule getXFeatureCallRule() {
		return getXFeatureCallAccess().getRule();
	}

	//IdOrSuper:
	//
	//	ValidID | "super";
	public XbaseGrammarAccess.IdOrSuperElements getIdOrSuperAccess() {
		return gaXbase.getIdOrSuperAccess();
	}
	
	public ParserRule getIdOrSuperRule() {
		return getIdOrSuperAccess().getRule();
	}

	//// This is a workaround since ANTLR will not be able to resolve
	//
	//
	//// StaticQualifier: ValidID ('::' ValidID)*; and XFeatureCall: (StaticQualifier '::')? ValidID
	//
	//
	//// Make sure to change the value converter if you change the syntax of the StaticQualifier
	// StaticQualifier:
	//
	//	(ValidID "::")+;
	public XbaseGrammarAccess.StaticQualifierElements getStaticQualifierAccess() {
		return gaXbase.getStaticQualifierAccess();
	}
	
	public ParserRule getStaticQualifierRule() {
		return getStaticQualifierAccess().getRule();
	}

	//XConstructorCall returns XExpression:
	//
	//	{XConstructorCall} "new" constructor=[types::JvmConstructor|QualifiedName] ("<"
	//
	//	typeArguments+=JvmArgumentTypeReference ("," typeArguments+=JvmArgumentTypeReference)* ">")? ("("
	//
	//	(arguments+=XShortClosure | arguments+=XExpression ("," arguments+=XExpression)*)? ")")? arguments+=XClosure?;
	public XbaseGrammarAccess.XConstructorCallElements getXConstructorCallAccess() {
		return gaXbase.getXConstructorCallAccess();
	}
	
	public ParserRule getXConstructorCallRule() {
		return getXConstructorCallAccess().getRule();
	}

	//XBooleanLiteral returns XExpression:
	//
	//	{XBooleanLiteral} ("false" | isTrue?="true");
	public XbaseGrammarAccess.XBooleanLiteralElements getXBooleanLiteralAccess() {
		return gaXbase.getXBooleanLiteralAccess();
	}
	
	public ParserRule getXBooleanLiteralRule() {
		return getXBooleanLiteralAccess().getRule();
	}

	//XNullLiteral returns XExpression:
	//
	//	{XNullLiteral} "null";
	public XbaseGrammarAccess.XNullLiteralElements getXNullLiteralAccess() {
		return gaXbase.getXNullLiteralAccess();
	}
	
	public ParserRule getXNullLiteralRule() {
		return getXNullLiteralAccess().getRule();
	}

	//XNumberLiteral returns XExpression:
	//
	//	{XNumberLiteral} value=Number;
	public XbaseGrammarAccess.XNumberLiteralElements getXNumberLiteralAccess() {
		return gaXbase.getXNumberLiteralAccess();
	}
	
	public ParserRule getXNumberLiteralRule() {
		return getXNumberLiteralAccess().getRule();
	}

	//XStringLiteral returns XExpression:
	//
	//	{XStringLiteral} value=STRING;
	public XbaseGrammarAccess.XStringLiteralElements getXStringLiteralAccess() {
		return gaXbase.getXStringLiteralAccess();
	}
	
	public ParserRule getXStringLiteralRule() {
		return getXStringLiteralAccess().getRule();
	}

	//XTypeLiteral returns XExpression:
	//
	//	{XTypeLiteral} "typeof" "(" type=[types::JvmType|QualifiedName] ")";
	public XbaseGrammarAccess.XTypeLiteralElements getXTypeLiteralAccess() {
		return gaXbase.getXTypeLiteralAccess();
	}
	
	public ParserRule getXTypeLiteralRule() {
		return getXTypeLiteralAccess().getRule();
	}

	//XThrowExpression returns XExpression:
	//
	//	{XThrowExpression} "throw" expression=XExpression;
	public XbaseGrammarAccess.XThrowExpressionElements getXThrowExpressionAccess() {
		return gaXbase.getXThrowExpressionAccess();
	}
	
	public ParserRule getXThrowExpressionRule() {
		return getXThrowExpressionAccess().getRule();
	}

	//XReturnExpression returns XExpression:
	//
	//	{XReturnExpression} "return" => expression=XExpression?;
	public XbaseGrammarAccess.XReturnExpressionElements getXReturnExpressionAccess() {
		return gaXbase.getXReturnExpressionAccess();
	}
	
	public ParserRule getXReturnExpressionRule() {
		return getXReturnExpressionAccess().getRule();
	}

	//XTryCatchFinallyExpression returns XExpression:
	//
	//	{XTryCatchFinallyExpression} "try" expression=XExpression (catchClauses+=XCatchClause+ ("finally"
	//
	//	finallyExpression=XExpression)? | "finally" finallyExpression=XExpression);
	public XbaseGrammarAccess.XTryCatchFinallyExpressionElements getXTryCatchFinallyExpressionAccess() {
		return gaXbase.getXTryCatchFinallyExpressionAccess();
	}
	
	public ParserRule getXTryCatchFinallyExpressionRule() {
		return getXTryCatchFinallyExpressionAccess().getRule();
	}

	//XCatchClause:
	//
	//	"catch" "(" declaredParam=FullJvmFormalParameter ")" expression=XExpression;
	public XbaseGrammarAccess.XCatchClauseElements getXCatchClauseAccess() {
		return gaXbase.getXCatchClauseAccess();
	}
	
	public ParserRule getXCatchClauseRule() {
		return getXCatchClauseAccess().getRule();
	}

	//QualifiedName:
	//
	//	ValidID ("." ValidID)*;
	public XbaseGrammarAccess.QualifiedNameElements getQualifiedNameAccess() {
		return gaXbase.getQualifiedNameAccess();
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//Number hidden():
	//
	//	HEX | (INT | DECIMAL) ("." (INT | DECIMAL))?;
	public XbaseGrammarAccess.NumberElements getNumberAccess() {
		return gaXbase.getNumberAccess();
	}
	
	public ParserRule getNumberRule() {
		return getNumberAccess().getRule();
	}

	//terminal HEX:
	//
	//	("0x" | "0X") ("0".."9" | "a".."f" | "A".."F" | "_")+ ("#" (("b" | "B") ("i" | "I") | ("l" | "L")))?;
	public TerminalRule getHEXRule() {
		return gaXbase.getHEXRule();
	} 

	//terminal INT returns ecore::EInt:
	//
	//	"0".."9" ("0".."9" | "_")*;
	public TerminalRule getINTRule() {
		return gaXbase.getINTRule();
	} 

	//terminal DECIMAL:
	//
	//	INT (("e" | "E") ("+" | "-")? INT)? (("b" | "B") ("i" | "I" | "d" | "D") | ("l" | "L" | "d" | "D" | "f" | "F"))?;
	public TerminalRule getDECIMALRule() {
		return gaXbase.getDECIMALRule();
	} 

	//JvmTypeReference:
	//
	//	JvmParameterizedTypeReference => ({JvmGenericArrayTypeReference.componentType=current} "[" "]")* | XFunctionTypeRef;
	public XtypeGrammarAccess.JvmTypeReferenceElements getJvmTypeReferenceAccess() {
		return gaXbase.getJvmTypeReferenceAccess();
	}
	
	public ParserRule getJvmTypeReferenceRule() {
		return getJvmTypeReferenceAccess().getRule();
	}

	//XFunctionTypeRef:
	//
	//	("(" (paramTypes+=JvmTypeReference ("," paramTypes+=JvmTypeReference)*)? ")")? "=>" returnType=JvmTypeReference;
	public XtypeGrammarAccess.XFunctionTypeRefElements getXFunctionTypeRefAccess() {
		return gaXbase.getXFunctionTypeRefAccess();
	}
	
	public ParserRule getXFunctionTypeRefRule() {
		return getXFunctionTypeRefAccess().getRule();
	}

	//JvmParameterizedTypeReference:
	//
	//	type=[JvmType|QualifiedName] ("<" arguments+=JvmArgumentTypeReference ("," arguments+=JvmArgumentTypeReference)*
	//
	//	">")?;
	public XtypeGrammarAccess.JvmParameterizedTypeReferenceElements getJvmParameterizedTypeReferenceAccess() {
		return gaXbase.getJvmParameterizedTypeReferenceAccess();
	}
	
	public ParserRule getJvmParameterizedTypeReferenceRule() {
		return getJvmParameterizedTypeReferenceAccess().getRule();
	}

	//JvmArgumentTypeReference returns JvmTypeReference:
	//
	//	JvmTypeReference | JvmWildcardTypeReference;
	public XtypeGrammarAccess.JvmArgumentTypeReferenceElements getJvmArgumentTypeReferenceAccess() {
		return gaXbase.getJvmArgumentTypeReferenceAccess();
	}
	
	public ParserRule getJvmArgumentTypeReferenceRule() {
		return getJvmArgumentTypeReferenceAccess().getRule();
	}

	//JvmWildcardTypeReference:
	//
	//	{JvmWildcardTypeReference} "?" (constraints+=JvmUpperBound | constraints+=JvmLowerBound)?;
	public XtypeGrammarAccess.JvmWildcardTypeReferenceElements getJvmWildcardTypeReferenceAccess() {
		return gaXbase.getJvmWildcardTypeReferenceAccess();
	}
	
	public ParserRule getJvmWildcardTypeReferenceRule() {
		return getJvmWildcardTypeReferenceAccess().getRule();
	}

	//JvmUpperBound:
	//
	//	"extends" typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmUpperBoundElements getJvmUpperBoundAccess() {
		return gaXbase.getJvmUpperBoundAccess();
	}
	
	public ParserRule getJvmUpperBoundRule() {
		return getJvmUpperBoundAccess().getRule();
	}

	//JvmUpperBoundAnded returns JvmUpperBound:
	//
	//	"&" typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmUpperBoundAndedElements getJvmUpperBoundAndedAccess() {
		return gaXbase.getJvmUpperBoundAndedAccess();
	}
	
	public ParserRule getJvmUpperBoundAndedRule() {
		return getJvmUpperBoundAndedAccess().getRule();
	}

	//JvmLowerBound:
	//
	//	"super" typeReference=JvmTypeReference;
	public XtypeGrammarAccess.JvmLowerBoundElements getJvmLowerBoundAccess() {
		return gaXbase.getJvmLowerBoundAccess();
	}
	
	public ParserRule getJvmLowerBoundRule() {
		return getJvmLowerBoundAccess().getRule();
	}

	//JvmTypeParameter:
	//
	//	name=ValidID (constraints+=JvmUpperBound constraints+=JvmUpperBoundAnded* | constraints+=JvmLowerBound)?;
	public XtypeGrammarAccess.JvmTypeParameterElements getJvmTypeParameterAccess() {
		return gaXbase.getJvmTypeParameterAccess();
	}
	
	public ParserRule getJvmTypeParameterRule() {
		return getJvmTypeParameterAccess().getRule();
	}

	//ValidID:
	//
	//	ID;
	public XtypeGrammarAccess.ValidIDElements getValidIDAccess() {
		return gaXbase.getValidIDAccess();
	}
	
	public ParserRule getValidIDRule() {
		return getValidIDAccess().getRule();
	}

	//terminal ID:
	//
	//	"^"? ("a".."z" | "A".."Z" | "$" | "_") ("a".."z" | "A".."Z" | "$" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaXbase.getIDRule();
	} 

	//terminal STRING:
	//
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaXbase.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaXbase.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaXbase.getSL_COMMENTRule();
	} 

	//terminal WS:
	//
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaXbase.getWSRule();
	} 

	//terminal ANY_OTHER:
	//
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaXbase.getANY_OTHERRule();
	} 
}
