/*
* generated by Xtext
*/
package de.nie.fin.ui.contentassist;

import de.nie.fin.ui.contentassist.AbstractFinProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class FinProposalProvider extends AbstractFinProposalProvider {

}
