/*
 * generated by Xtext
 */
package de.nie.fin.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FinUiModule extends de.nie.fin.ui.AbstractFinUiModule {
	public FinUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
