/*
 * generated by Xtext
 */
package de.nie.fin;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FinRuntimeModule extends de.nie.fin.AbstractFinRuntimeModule {

}
