/*
* generated by Xtext
*/
package de.nie.fin.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.nie.fin.services.FinGrammarAccess;

public class FinParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private FinGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.nie.fin.parser.antlr.internal.InternalFinParser createParser(XtextTokenStream stream) {
		return new de.nie.fin.parser.antlr.internal.InternalFinParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "FinModelFile";
	}
	
	public FinGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(FinGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
