/*
 * generated by Xtext
 */
package de.nie.fin.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.nie.fin.ui.internal.FinActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FinExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FinActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return FinActivator.getInstance().getInjector(FinActivator.DE_NIE_FIN_FIN);
	}
	
}
